# 01 Getting & Knowing Data

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv', sep = "\t")

Q01 Îç∞Ïù¥ÌÑ∞Î•º Î°úÎìúÌïòÎùº. Îç∞Ïù¥ÌÑ∞Îäî \tÏùÑ Í∏∞Ï§ÄÏúºÎ°ú Íµ¨Î∂ÑÎêòÏñ¥ÏûàÎã§.

In [ ]:
df

gameId   creationTime  gameDuration  seasonId  winner  firstBlood  \
0      3326086514  1504279457970          1949         9       1           2   
1      3229566029  1497848803862          1851         9       1           1   
2      3327363504  1504360103310          1493         9       1           2   
3      3326856598  1504348503996          1758         9       1           1   
4      3330080762  1504554410899          2094         9       1           2   
...           ...            ...           ...       ...     ...         ...   
51485  3308904636  1503076540231          1944         9       2           1   
51486  3215685759  1496957179355          3304         9       2           1   
51487  3322765040  1504029863961          2156         9       2           2   
51488  3256675373  1499562036246          1475         9       2           2   
51489  3317333020  1503612754059          1445         9       1           1   

       firstTower  firstInhibitor  firstBaron  firstDragon  ...  \
0               1               1           1            1  ...   
1               1               1           0            1  ...   
2               1               1           1            2  ...   
3               1               1           1            1  ...   
4               1               1           1            1  ...   
...           ...             ...         ...          ...  ...   
51485           2               2           0            2  ...   
51486           1               2           2            2  ...   
51487           2               2           0            1  ...   
51488           2               2           0            2  ...   
51489           1               1           1            2  ...   

       t2_towerKills  t2_inhibitorKills  t2_baronKills  t2_dragonKills  \
0                  5                  0              0               1   
1                  2                  0              0               0   
2                  2                  0              0               1   
3                  0                  0              0               0   
4                  3                  0              0               1   
...              ...                ...            ...             ...   
51485             10                  2              0               4   
51486             11                  7              4               4   
51487             10                  2              0               2   
51488             11                  3              0               1   
51489              1                  0              0               1   

       t2_riftHeraldKills  t2_ban1  t2_ban2  t2_ban3  t2_ban4  t2_ban5  
0                       1      114       67       43       16       51  
1                       0       11       67      238       51      420  
2                       0      157      238      121       57       28  
3                       0      164       18      141       40       51  
4                       0       86       11      201      122       18  
...                   ...      ...      ...      ...      ...      ...  
51485                   0       55       -1       90      238      157  
51486                   1      157       55      119      154      105  
51487                   0      113      122       53       11      157  
51488                   0      154       39       51       90      114  
51489                   0       11      157      141       31       18  

[51490 rows x 61 columns]

Q02 Îç∞Ïù¥ÌÑ∞Ïùò ÏÉÅÏúÑ 5Í∞ú ÌñâÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.head(5)

gameId   creationTime  gameDuration  seasonId  winner  firstBlood  \
0  3326086514  1504279457970          1949         9       1           2   
1  3229566029  1497848803862          1851         9       1           1   
2  3327363504  1504360103310          1493         9       1           2   
3  3326856598  1504348503996          1758         9       1           1   
4  3330080762  1504554410899          2094         9       1           2   

   firstTower  firstInhibitor  firstBaron  firstDragon  ...  t2_towerKills  \
0           1               1           1            1  ...              5   
1           1               1           0            1  ...              2   
2           1               1           1            2  ...              2   
3           1               1           1            1  ...              0   
4           1               1           1            1  ...              3   

   t2_inhibitorKills  t2_baronKills  t2_dragonKills  t2_riftHeraldKills  \
0                  0              0               1                   1   
1                  0              0               0                   0   
2                  0              0               1                   0   
3                  0              0               0                   0   
4                  0              0               1                   0   

   t2_ban1  t2_ban2  t2_ban3  t2_ban4  t2_ban5  
0      114       67       43       16       51  
1       11       67      238       51      420  
2      157      238      121       57       28  
3      164       18      141       40       51  
4       86       11      201      122       18  

[5 rows x 61 columns]

Q03 Îç∞Ïù¥ÌÑ∞Ïùò ÌñâÍ≥º Ïó¥Ïùò Í∞ØÏàòÎ•º ÌååÏïÖÌïòÎùº

In [ ]:
df.shape
print("Ìñâ: ", df.shape[0])
print("Ïó¥: ", df.shape[1])


Ìñâ:  51490
Ïó¥:  61


Q04 Ï†ÑÏ≤¥ Ïª¨ÎüºÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.columns

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHer

Q05 6Î≤àÏß∏ Ïª¨ÎüºÎ™ÖÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.columns[5]

'firstBlood'

Q06 6Î≤àÏß∏ Ïª¨ÎüºÏùò Îç∞Ïù¥ÌÑ∞ ÌÉÄÏûÖÏùÑ ÌôïÏù∏ÌïòÎùº

In [ ]:
df.iloc[:,5].dtype

dtype('int64')

Q07 Îç∞Ïù¥ÌÑ∞ÏÖãÏùò Ïù∏Îç±Ïä§ Íµ¨ÏÑ±ÏùÄ Ïñ¥Îñ§Í∞Ä

In [ ]:
df.index

RangeIndex(start=0, stop=51490, step=1)

Q08 6Î≤àÏß∏ Ïª¨ÎüºÏùò 3Î≤àÏß∏ Í∞íÏùÄ Î¨¥ÏóáÏù∏Í∞Ä?

In [ ]:
df.iloc[2,5]

np.int64(2)

Q09 Îç∞Ïù¥ÌÑ∞Î•º Î°úÎìúÌïòÎùº. Ïª¨ÎüºÏù¥ ÌïúÍ∏ÄÏù¥Í∏∞Ïóê Ï†ÅÏ†àÌïú Ï≤òÎ¶¨Ìï¥Ï§òÏïºÌï®

In [ ]:
DataUrl = 'https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv'
df = pd.read_csv(DataUrl,encoding='euc-kr')

Q10 Îç∞Ïù¥ÌÑ∞ ÎßàÏßÄÎßâ 3Í∞úÌñâÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.tail(3)

id          ÏùºÏûê   ÏãúÎèÑÎ™Ö ÏùçÎ©¥ÎèôÎ™Ö         Í±∞Ï£ºÏù∏Íµ¨       Í∑ºÎ¨¥Ïù∏Íµ¨        Î∞©Î¨∏Ïù∏Íµ¨  \
9618  32066  2020-04-30   Ï†úÏ£ºÏãú  ÎèÑÎëêÎèô    28397.481   3144.895   84052.697   
9619  32067  2020-04-30  ÏÑúÍ∑ÄÌè¨Ïãú  ÏïàÎçïÎ©¥   348037.846  29106.286  251129.660   
9620  32068  2020-04-30   Ï†úÏ£ºÏãú   Ïó∞Îèô  1010643.372  65673.477  447622.068   

           Ï¥ù Ïú†ÎèôÏù∏Íµ¨   ÌèâÍ∑† ÏÜçÎèÑ  ÌèâÍ∑† ÏÜåÏöî ÏãúÍ∞Ñ  ÌèâÍ∑† Í∏∞Ïò®  ÏùºÍ∞ïÏàòÎüâ  ÌèâÍ∑† ÌíçÏÜç  
9618   115595.073  41.053    29.421   20.3   0.0    3.0  
9619   628273.792  46.595    49.189   17.6   0.0    3.5  
9620  1523938.917  40.863    27.765   14.1   0.0    4.8

Q11 ÏàòÏπòÌòï Î≥ÄÏàòÎ•º Í∞ÄÏßÑ Ïª¨ÎüºÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.select_dtypes(exclude=object).columns

Index(['id', 'Í±∞Ï£ºÏù∏Íµ¨', 'Í∑ºÎ¨¥Ïù∏Íµ¨', 'Î∞©Î¨∏Ïù∏Íµ¨', 'Ï¥ù Ïú†ÎèôÏù∏Íµ¨', 'ÌèâÍ∑† ÏÜçÎèÑ', 'ÌèâÍ∑† ÏÜåÏöî ÏãúÍ∞Ñ', 'ÌèâÍ∑† Í∏∞Ïò®',
       'ÏùºÍ∞ïÏàòÎüâ', 'ÌèâÍ∑† ÌíçÏÜç'],
      dtype='object')

Q12 Î≤îÏ£ºÌòï Î≥ÄÏàòÎ•º Í∞ÄÏßÑ Ïª¨ÎüºÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.select_dtypes(include = object).columns

Index(['ÏùºÏûê', 'ÏãúÎèÑÎ™Ö', 'ÏùçÎ©¥ÎèôÎ™Ö'], dtype='object')

Q13 Í∞Å Ïª¨ÎüºÏùò Í≤∞Ï∏°Ïπò Ïà´ÏûêÎ•º ÌååÏïÖÌïòÎùº

In [ ]:
df.isnull().sum()

id          0
ÏùºÏûê          0
ÏãúÎèÑÎ™Ö         0
ÏùçÎ©¥ÎèôÎ™Ö        0
Í±∞Ï£ºÏù∏Íµ¨        0
Í∑ºÎ¨¥Ïù∏Íµ¨        0
Î∞©Î¨∏Ïù∏Íµ¨        0
Ï¥ù Ïú†ÎèôÏù∏Íµ¨      0
ÌèâÍ∑† ÏÜçÎèÑ       0
ÌèâÍ∑† ÏÜåÏöî ÏãúÍ∞Ñ    0
ÌèâÍ∑† Í∏∞Ïò®       0
ÏùºÍ∞ïÏàòÎüâ        0
ÌèâÍ∑† ÌíçÏÜç       0
dtype: int64

Q14 Í∞Å Ïª¨ÎüºÏùò Îç∞Ïù¥ÌÑ∞Ïàò, Îç∞Ïù¥ÌÑ∞ÌÉÄÏûÖÏùÑ ÌïúÎ≤àÏóê ÌôïÏù∏ÌïòÎùº

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   id        9621 non-null   int64  
 1   ÏùºÏûê        9621 non-null   object 
 2   ÏãúÎèÑÎ™Ö       9621 non-null   object 
 3   ÏùçÎ©¥ÎèôÎ™Ö      9621 non-null   object 
 4   Í±∞Ï£ºÏù∏Íµ¨      9621 non-null   float64
 5   Í∑ºÎ¨¥Ïù∏Íµ¨      9621 non-null   float64
 6   Î∞©Î¨∏Ïù∏Íµ¨      9621 non-null   float64
 7   Ï¥ù Ïú†ÎèôÏù∏Íµ¨    9621 non-null   float64
 8   ÌèâÍ∑† ÏÜçÎèÑ     9621 non-null   float64
 9   ÌèâÍ∑† ÏÜåÏöî ÏãúÍ∞Ñ  9621 non-null   float64
 10  ÌèâÍ∑† Í∏∞Ïò®     9621 non-null   float64
 11  ÏùºÍ∞ïÏàòÎüâ      9621 non-null   float64
 12  ÌèâÍ∑† ÌíçÏÜç     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB


Q15 Í∞Å ÏàòÏπòÌòï Î≥ÄÏàòÏùò Î∂ÑÌè¨(ÏÇ¨Î∂ÑÏúÑ, ÌèâÍ∑†, ÌëúÏ§ÄÌé∏Ï∞®, ÏµúÎåÄ , ÏµúÏÜå)Î•º ÌôïÏù∏ÌïòÎùº

In [ ]:
df.describe()

id          Í±∞Ï£ºÏù∏Íµ¨           Í∑ºÎ¨¥Ïù∏Íµ¨           Î∞©Î¨∏Ïù∏Íµ¨        Ï¥ù Ïú†ÎèôÏù∏Íµ¨  \
count   9621.000000  9.621000e+03    9621.000000    9621.000000  9.621000e+03   
mean   27258.000000  3.174315e+05   35471.201510  195889.561802  5.487922e+05   
std     2777.487804  2.982079e+05   40381.214775  140706.090325  4.608802e+05   
min    22448.000000  9.305552e+03    1407.936000   11538.322000  2.225181e+04   
25%    24853.000000  9.539939e+04   12074.498000   99632.153000  2.216910e+05   
50%    27258.000000  2.221105e+05   21960.928000  152805.335000  3.866935e+05   
75%    29663.000000  4.106671e+05   40192.032000  236325.109000  6.406918e+05   
max    32068.000000  1.364504e+06  263476.965000  723459.209000  2.066484e+06   

             ÌèâÍ∑† ÏÜçÎèÑ     ÌèâÍ∑† ÏÜåÏöî ÏãúÍ∞Ñ        ÌèâÍ∑† Í∏∞Ïò®         ÏùºÍ∞ïÏàòÎüâ        ÌèâÍ∑† ÌíçÏÜç  
count  9621.000000  9621.000000  9621.000000  9621.000000  9621.000000  
mean     41.109084    37.215873    13.550828     6.972426     2.753171  
std       8.758631    12.993786     7.745515    27.617260     1.498538  
min      24.333000    12.667000    -9.600000     0.000000     0.000000  
25%      34.250000    27.889000     7.600000     0.000000     1.700000  
50%      39.640000    34.500000    13.400000     0.000000     2.400000  
75%      49.105000    46.176000    19.700000     1.500000     3.400000  
max     103.000000   172.200000    30.400000   587.500000    13.333000

Q16 Í±∞Ï£ºÏù∏Íµ¨ Ïª¨ÎüºÏùò Í∞íÎì§ÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df['Í±∞Ï£ºÏù∏Íµ¨']

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...     
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: Í±∞Ï£ºÏù∏Íµ¨, Length: 9621, dtype: float64

Q17 ÌèâÍ∑† ÏÜçÎèÑ Ïª¨ÎüºÏùò 4Î∂ÑÏúÑ Î≤îÏúÑ(IQR) Í∞íÏùÑ Íµ¨ÌïòÏó¨Îùº

IQR >>> .quantile


In [ ]:
 df['ÌèâÍ∑† ÏÜçÎèÑ'].quantile(0.75) -df['ÌèâÍ∑† ÏÜçÎèÑ'].quantile(0.25)

np.float64(14.854999999999997)

Q18 ÏùçÎ©¥ÎèôÎ™Ö Ïª¨ÎüºÏùò Ïú†ÏùºÍ∞í Í∞ØÏàòÎ•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
len(df['ÏùçÎ©¥ÎèôÎ™Ö'].unique())

41

Q19 ÏùçÎ©¥ÎèôÎ™Ö Ïª¨ÎüºÏùò Ïú†ÏùºÍ∞íÏùÑ Î™®Îëê Ï∂úÎ†•ÌïòÎùº

In [ ]:
df['ÏùçÎ©¥ÎèôÎ™Ö'].unique()

array(['ÎèÑÎëêÎèô', 'Ïô∏ÎèÑÎèô', 'Ïù¥ÎèÑ2Îèô', 'ÏùºÎèÑ1Îèô', 'ÎåÄÏ≤úÎèô', 'ÏÑúÌôçÎèô', 'ÌïúÍ≤ΩÎ©¥', 'ÏÜ°ÏÇ∞Îèô', 'Ï°∞Ï≤úÏùç',
       'ÏùºÎèÑ2Îèô', 'ÏòÅÏ≤úÎèô', 'ÏòàÎûòÎèô', 'ÎåÄÎ•úÎèô', 'ÏÇºÎèÑ1Îèô', 'Ïù¥Ìò∏Îèô', 'Í±¥ÏûÖÎèô', 'Ï§ëÏïôÎèô', 'ÏÇºÏñëÎèô',
       'ÏÇºÎèÑ2Îèô', 'Ïù¥ÎèÑ1Îèô', 'ÎÇ®ÏõêÏùç', 'ÎåÄÏ†ïÏùç', 'Ï†ïÎ∞©Îèô', 'Ìö®ÎèàÎèô', 'ÏïÑÎùºÎèô', 'ÌïúÎ¶ºÏùç', 'Íµ¨Ï¢åÏùç',
       'Ïö©Îã¥1Îèô', 'Ïò§ÎùºÎèô', 'ÌôîÎ∂ÅÎèô', 'Ïó∞Îèô', 'ÌëúÏÑ†Î©¥', 'Ï§ëÎ¨∏Îèô', 'ÏÑ±ÏÇ∞Ïùç', 'ÏïàÎçïÎ©¥', 'Ï≤úÏßÄÎèô',
       'ÎÖ∏ÌòïÎèô', 'ÎèôÌôçÎèô', 'Ïö©Îã¥2Îèô', 'Î¥âÍ∞úÎèô', 'Ïï†ÏõîÏùç'], dtype=object)

# 02 Filtering & Sorting

In [ ]:
import pandas as pd

Q20 Îç∞Ïù¥ÌÑ∞Î•º Î°úÎìúÌïòÎùº.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv')

df

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]     $3.39   
2                                               [Apple]     $3.39   
3                                                   NaN     $2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 5 columns]

Q21 quantityÏª¨Îüº Í∞íÏù¥ 3Ïù∏ Îç∞Ïù¥ÌÑ∞Î•º Ï∂îÏ∂úÌïòÏó¨ Ï≤´ 5ÌñâÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df[df['quantity'] == 3].head(5)

order_id  quantity          item_name  \
409       178         3       Chicken Bowl   
445       193         3               Bowl   
689       284         3  Canned Soft Drink   
818       338         3      Bottled Water   
850       350         3  Canned Soft Drink   

                                    choice_description item_price  
409  [[Fresh Tomato Salsa (Mild), Tomatillo-Green C...    $32.94   
445  [Braised Carnitas, Pinto Beans, [Sour Cream, C...    $22.20   
689                                        [Diet Coke]     $3.75   
818                                                NaN     $3.27   
850                                           [Sprite]     $3.75

Q22 quantityÏª¨Îüº Í∞íÏù¥ 3Ïù∏ Îç∞Ïù¥ÌÑ∞Î•º Ï∂îÏ∂úÌïòÏó¨ indexÎ•º 0Î∂ÄÌÑ∞ Ï†ïÎ†¨ÌïòÍ≥† Ï≤´ 5ÌñâÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df[df['quantity'] == 3].reset_index(0).head(5)

index  order_id  quantity          item_name  \
0    409       178         3       Chicken Bowl   
1    445       193         3               Bowl   
2    689       284         3  Canned Soft Drink   
3    818       338         3      Bottled Water   
4    850       350         3  Canned Soft Drink   

                                  choice_description item_price  
0  [[Fresh Tomato Salsa (Mild), Tomatillo-Green C...    $32.94   
1  [Braised Carnitas, Pinto Beans, [Sour Cream, C...    $22.20   
2                                        [Diet Coke]     $3.75   
3                                                NaN     $3.27   
4                                           [Sprite]     $3.75

Q23 quantity , item_price ÎëêÍ∞úÏùò Ïª¨ÎüºÏúºÎ°ú Íµ¨ÏÑ±Îêú ÏÉàÎ°úÏö¥ Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏùÑ Ï†ïÏùòÌïòÎùº

In [ ]:
result_df = df[['quantity','item_price']]

result_df

quantity item_price
0            1     $2.39 
1            1     $3.39 
2            1     $3.39 
3            1     $2.39 
4            2    $16.98 
...        ...        ...
4617         1    $11.75 
4618         1    $11.75 
4619         1    $11.25 
4620         1     $8.75 
4621         1     $8.75 

[4622 rows x 2 columns]

Q24 item_price Ïª¨ÎüºÏùò Îã¨Îü¨ÌëúÏãú Î¨∏ÏûêÎ•º Ï†úÍ±∞ÌïòÍ≥† float ÌÉÄÏûÖÏúºÎ°ú Ï†ÄÏû•ÌïòÏó¨ new_price Ïª¨ÎüºÏóê Ï†ÄÏû•ÌïòÎùº

df['new_price'] = df['item_price'].str[1:].astype('float')
Ans = df['new_price'].head()

In [ ]:
df['new_price'] = df['item_price'].str.replace("$", "", regex=False).astype(float)
df

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  new_price  
0                                                   NaN     $2.39        2.39  
1                                          [Clementine]     $3.39        3.39  
2                                               [Apple]     $3.39        3.39  
3                                                   NaN     $2.39        2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98       16.98  
...                                                 ...        ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75       11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25       11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75        8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75        8.75  

[4622 rows x 6 columns]

Q25 new_price Ïª¨ÎüºÏù¥ 5Ïù¥ÌïòÏùò Í∞íÏùÑ Í∞ÄÏßÄÎäî Îç∞Ïù¥ÌÑ∞ÌîÑÎ†àÏûÑÏùÑ Ï∂îÏ∂úÌïòÍ≥†, Ï†ÑÏ≤¥ Í∞ØÏàòÎ•º Íµ¨ÌïòÏó¨Îùº

In [ ]:
len(df[df['new_price'] <= 5])

1652

Q26 item_nameÎ™ÖÏù¥ Chicken Salad Bowl Ïù∏ Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏùÑ Ï∂îÏ∂úÌïòÎùºÍ≥† index Í∞íÏùÑ Ï¥àÍ∏∞Ìôî ÌïòÏó¨Îùº

In [ ]:
df[df['item_name'] == 'Chicken Salad Bowl'].reset_index(drop=True)

order_id  quantity           item_name  \
0          20         1  Chicken Salad Bowl   
1          60         2  Chicken Salad Bowl   
2          94         2  Chicken Salad Bowl   
3         111         1  Chicken Salad Bowl   
4         137         2  Chicken Salad Bowl   
..        ...       ...                 ...   
105      1813         2  Chicken Salad Bowl   
106      1822         1  Chicken Salad Bowl   
107      1834         1  Chicken Salad Bowl   
108      1834         1  Chicken Salad Bowl   
109      1834         1  Chicken Salad Bowl   

                                    choice_description item_price  new_price  
0    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75        8.75  
1    [Tomatillo Green Chili Salsa, [Sour Cream, Che...    $22.50       22.50  
2    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $22.50       22.50  
3    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $8.75        8.75  
4              [Fresh Tomato Salsa, Fajita Vegetables]    $17.50       17.50  
..                                                 ...        ...        ...  
105  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $17.50       17.50  
106  [Fresh Tomato Salsa, [Black Beans, Cheese, Gua...    $11.25       11.25  
107  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25       11.25  
108  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75        8.75  
109  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75        8.75  

[110 rows x 6 columns]

Q2 7
new_priceÍ∞íÏù¥ 9 Ïù¥ÌïòÏù¥Í≥† item_name Í∞íÏù¥ Chicken Salad Bowl Ïù∏ Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏùÑ Ï∂îÏ∂úÌïòÎùº

In [ ]:
df[(df['new_price'] <= 9) & (df['item_name'] == 'Chicken Salad Bowl')]

order_id  quantity           item_name  \
44          20         1  Chicken Salad Bowl   
256        111         1  Chicken Salad Bowl   
526        220         1  Chicken Salad Bowl   
528        221         1  Chicken Salad Bowl   
529        221         1  Chicken Salad Bowl   
568        234         1  Chicken Salad Bowl   
585        240         1  Chicken Salad Bowl   
693        286         1  Chicken Salad Bowl   
702        289         1  Chicken Salad Bowl   
762        314         1  Chicken Salad Bowl   
1109       458         1  Chicken Salad Bowl   
1460       592         1  Chicken Salad Bowl   
1471       598         1  Chicken Salad Bowl   
1483       602         1  Chicken Salad Bowl   
1547       628         1  Chicken Salad Bowl   
1601       649         1  Chicken Salad Bowl   
1621       654         1  Chicken Salad Bowl   
1756       709         1  Chicken Salad Bowl   
1977       798         1  Chicken Salad Bowl   
2031       818         1  Chicken Salad Bowl   
2113       850         1  Chicken Salad Bowl   
2224       896         1  Chicken Salad Bowl   
2314       926         1  Chicken Salad Bowl   
2728      1083         1  Chicken Salad Bowl   
2858      1136         1  Chicken Salad Bowl   
2883      1145         1  Chicken Salad Bowl   
2897      1152         1  Chicken Salad Bowl   
2989      1189         1  Chicken Salad Bowl   
3033      1206         1  Chicken Salad Bowl   
3069      1222         1  Chicken Salad Bowl   
3117      1243         1  Chicken Salad Bowl   
3259      1305         1  Chicken Salad Bowl   
3261      1305         1  Chicken Salad Bowl   
3310      1327         1  Chicken Salad Bowl   
3315      1329         1  Chicken Salad Bowl   
3381      1357         1  Chicken Salad Bowl   
3411      1368         1  Chicken Salad Bowl   
3623      1450         1  Chicken Salad Bowl   
3656      1461         1  Chicken Salad Bowl   
3706      1483         1  Chicken Salad Bowl   
3712      1483         1  Chicken Salad Bowl   
3790      1517         1  Chicken Salad Bowl   
3798      1521         1  Chicken Salad Bowl   
3974      1592         1  Chicken Salad Bowl   
3997      1601         1  Chicken Salad Bowl   
4012      1606         1  Chicken Salad Bowl   
4035      1615         1  Chicken Salad Bowl   
4064      1627         1  Chicken Salad Bowl   
4205      1679         1  Chicken Salad Bowl   
4207      1679         1  Chicken Salad Bowl   
4333      1730         1  Chicken Salad Bowl   
4352      1738         1  Chicken Salad Bowl   
4439      1769         1  Chicken Salad Bowl   
4520      1797         1  Chicken Salad Bowl   
4620      1834         1  Chicken Salad Bowl   
4621      1834         1  Chicken Salad Bowl   

                                     choice_description item_price  new_price  
44    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75        8.75  
256   [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $8.75        8.75  
526   [Roasted Chili Corn Salsa, [Black Beans, Sour ...     $8.75        8.75  
528   [Tomatillo Green Chili Salsa, [Fajita Vegetabl...     $8.75        8.75  
529   [Tomatillo Green Chili Salsa, [Fajita Vegetabl...     $8.75        8.75  
568             [Fresh Tomato Salsa, Fajita Vegetables]     $8.75        8.75  
585             [Fresh Tomato Salsa, Fajita Vegetables]     $8.75        8.75  
693   [Fresh Tomato Salsa, [Sour Cream, Cheese, Lett...     $8.75        8.75  
702   [Tomatillo Red Chili Salsa, [Black Beans, Chee...     $8.75        8.75  
762   [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75        8.75  
1109  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $8.75        8.75  
1460                      [Fresh Tomato Salsa, Lettuce]     $8.75        8.75  
1471  [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75        8.75  
1483  [Fresh Tomato Salsa, [Fajita Vegetables, Chees...     $8.75        8.75  
1547  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $8.75    

Q28 dfÏùò new_price Ïª¨Îüº Í∞íÏóê Îî∞Îùº Ïò§Î¶ÑÏ∞®ÏàúÏúºÎ°ú Ï†ïÎ¶¨ÌïòÍ≥† indexÎ•º Ï¥àÍ∏∞Ìôî ÌïòÏó¨Îùº

In [ ]:
df.sort_values(by = 'new_price', ascending = True).reset_index()

index  order_id  quantity                     item_name  \
0        34        17         1                 Bottled Water   
1        53        24         1                   Canned Soda   
2       943       388         1                 Bottled Water   
3      1216       496         1                   Canned Soda   
4      1217       496         1                   Canned Soda   
...     ...       ...       ...                           ...   
4617   3601      1443         3                Veggie Burrito   
4618   3602      1443         4               Chicken Burrito   
4619   1254       511         4               Chicken Burrito   
4620   3480      1398         3                 Carnitas Bowl   
4621   3598      1443        15  Chips and Fresh Tomato Salsa   

                                     choice_description item_price  new_price  
0                                                   NaN     $1.09        1.09  
1                                              [Sprite]     $1.09        1.09  
2                                                   NaN     $1.09        1.09  
3                                           [Diet Coke]     $1.09        1.09  
4                                     [Diet Dr. Pepper]     $1.09        1.09  
...                                                 ...        ...        ...  
4617  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $33.75       33.75  
4618  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...    $35.00       35.00  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $35.00       35.00  
4620  [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $35.25       35.25  
4621                                                NaN    $44.25       44.25  

[4622 rows x 7 columns]

Q29 dfÏùò item_name Ïª¨Îüº Í∞íÏ§ë Chips Ìè¨Ìï®ÌïòÎäî Í≤ΩÏö∞Ïùò Îç∞Ïù¥ÌÑ∞Î•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.loc[df.item_name.str.contains("Chips")]

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
6            3         1                          Side of Chips   
10           5         1                    Chips and Guacamole   
14           7         1                    Chips and Guacamole   
...        ...       ...                                    ...   
4596      1826         1                    Chips and Guacamole   
4600      1827         1                    Chips and Guacamole   
4605      1828         1                    Chips and Guacamole   
4613      1831         1                                  Chips   
4616      1832         1                    Chips and Guacamole   

     choice_description item_price  new_price  
0                   NaN     $2.39        2.39  
3                   NaN     $2.39        2.39  
6                   NaN     $1.69        1.69  
10                  NaN     $4.45        4.45  
14                  NaN     $4.45        4.45  
...                 ...        ...        ...  
4596                NaN     $4.45        4.45  
4600                NaN     $4.45        4.45  
4605                NaN     $4.45        4.45  
4613                NaN     $2.15        2.15  
4616                NaN     $4.45        4.45  

[1084 rows x 6 columns]

Q30 dfÏùò ÏßùÏàòÎ≤àÏß∏ Ïª¨ÎüºÎßåÏùÑ Ìè¨Ìï®ÌïòÎäî Îç∞Ïù¥ÌÑ∞ÌîÑÎ†àÏûÑÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.iloc[:, ::2]

order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39 
1            1                                   Izze     $3.39 
2            1                       Nantucket Nectar     $3.39 
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39 
4            2                           Chicken Bowl    $16.98 
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75 
4618      1833                          Steak Burrito    $11.75 
4619      1834                     Chicken Salad Bowl    $11.25 
4620      1834                     Chicken Salad Bowl     $8.75 
4621      1834                     Chicken Salad Bowl     $8.75 

[4622 rows x 3 columns]

Q31 dfÏùò new_price Ïª¨Îüº Í∞íÏóê Îî∞Îùº ÎÇ¥Î¶ºÏ∞®ÏàúÏúºÎ°ú Ï†ïÎ¶¨ÌïòÍ≥† indexÎ•º Ï¥àÍ∏∞Ìôî ÌïòÏó¨Îùº

reset_index(), reset_index(drop = True)

In [ ]:
df.sort_values(by = 'new_price', ascending = False).reset_index(drop = True)

order_id  quantity                     item_name  \
0         1443        15  Chips and Fresh Tomato Salsa   
1         1398         3                 Carnitas Bowl   
2         1443         4               Chicken Burrito   
3          511         4               Chicken Burrito   
4         1443         3                Veggie Burrito   
...        ...       ...                           ...   
4617       435         1                   Canned Soda   
4618        51         1                   Canned Soda   
4619      1014         1                   Canned Soda   
4620      1009         1                   Canned Soda   
4621      1009         1                 Bottled Water   

                                     choice_description item_price  new_price  
0                                                   NaN    $44.25       44.25  
1     [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $35.25       35.25  
2     [Fresh Tomato Salsa, [Rice, Black Beans, Chees...    $35.00       35.00  
3     [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $35.00       35.00  
4     [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $33.75       33.75  
...                                                 ...        ...        ...  
4617                                     [Mountain Dew]     $1.09        1.09  
4618                                  [Diet Dr. Pepper]     $1.09        1.09  
4619                                        [Coca Cola]     $1.09        1.09  
4620                                        [Diet Coke]     $1.09        1.09  
4621                                                NaN     $1.09        1.09  

[4622 rows x 6 columns]

Q32 dfÏùò item_name Ïª¨Îüº Í∞íÏù¥ Steak Salad ÎòêÎäî Bowl Ïù∏ Îç∞Ïù¥ÌÑ∞Î•º Ïù∏Îç±Ïã±ÌïòÎùº

In [ ]:
df[df['item_name'].isin(['Steak Salad', 'Bowl'])].reset_index(drop = True)

order_id  quantity    item_name  \
0       193         3         Bowl   
1       276         1  Steak Salad   
2       279         1         Bowl   
3       311         1  Steak Salad   
4       369         1  Steak Salad   
5      1406         1  Steak Salad   

                                  choice_description item_price  new_price  
0  [Braised Carnitas, Pinto Beans, [Sour Cream, C...    $22.20       22.20  
1  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     $8.99        8.99  
2  [Adobo-Marinated and Grilled Steak, [Sour Crea...     $7.40        7.40  
3  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     $8.99        8.99  
4  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...     $8.99        8.99  
5                        [[Lettuce, Fajita Veggies]]     $8.69        8.69

Q33 dfÏùò item_name Ïª¨Îüº Í∞íÏù¥ Steak Salad ÎòêÎäî Bowl Ïù∏ Îç∞Ïù¥ÌÑ∞Î•º Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÌôî Ìïú ÌõÑ, item_nameÎ•º Í∏∞Ï§ÄÏúºÎ°ú Ï§ëÎ≥µÌñâÏù¥ ÏûàÏúºÎ©¥ Ï†úÍ±∞ÌïòÎêò Ï≤´Î≤àÏß∏ ÏºÄÏù¥Ïä§Îßå ÎÇ®Í≤®Îùº

In [ ]:
result = df[df['item_name'].isin(["Steak Salad", "Bowl"])]

result.drop_duplicates(subset = 'item_name', keep = 'first')

order_id  quantity    item_name  \
445       193         3         Bowl   
664       276         1  Steak Salad   

                                    choice_description item_price  new_price  
445  [Braised Carnitas, Pinto Beans, [Sour Cream, C...    $22.20       22.20  
664  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     $8.99        8.99

Q34 dfÏùò item_name Ïª¨Îüº Í∞íÏù¥ Steak Salad ÎòêÎäî Bowl Ïù∏ Îç∞Ïù¥ÌÑ∞Î•º Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÌôî Ìïú ÌõÑ, item_nameÎ•º Í∏∞Ï§ÄÏúºÎ°ú Ï§ëÎ≥µÌñâÏù¥ ÏûàÏúºÎ©¥ Ï†úÍ±∞ÌïòÎêò ÎßàÏßÄÎßâ ÏºÄÏù¥Ïä§Îßå ÎÇ®Í≤®Îùº

In [ ]:
result = df[df['item_name'].isin(["Steak Salad", "Bowl"])]

result.drop_duplicates(subset = 'item_name', keep = 'last')

order_id  quantity    item_name  \
673        279         1         Bowl   
3502      1406         1  Steak Salad   

                                     choice_description item_price  new_price  
673   [Adobo-Marinated and Grilled Steak, [Sour Crea...     $7.40        7.40  
3502                        [[Lettuce, Fajita Veggies]]     $8.69        8.69

Q35 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë new_priceÍ∞íÏù¥ new_priceÍ∞íÏùò ÌèâÍ∑†Í∞í Ïù¥ÏÉÅÏùÑ Í∞ÄÏßÄÎäî Îç∞Ïù¥ÌÑ∞Îì§ÏùÑ Ïù∏Îç±Ïã±ÌïòÎùº

In [ ]:
df[df['new_price'] >= df['new_price'].mean()].reset_index(drop = True)

order_id  quantity           item_name  \
0            2         2        Chicken Bowl   
1            3         1        Chicken Bowl   
2            4         1       Steak Burrito   
3            4         1    Steak Soft Tacos   
4            5         1       Steak Burrito   
...        ...       ...                 ...   
2885      1833         1       Steak Burrito   
2886      1833         1       Steak Burrito   
2887      1834         1  Chicken Salad Bowl   
2888      1834         1  Chicken Salad Bowl   
2889      1834         1  Chicken Salad Bowl   

                                     choice_description item_price  new_price  
0     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98       16.98  
1     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98       10.98  
2     [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75       11.75  
3     [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25        9.25  
4     [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25        9.25  
...                                                 ...        ...        ...  
2885  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75       11.75  
2886  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75       11.75  
2887  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25       11.25  
2888  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75        8.75  
2889  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75        8.75  

[2890 rows x 6 columns]

Q36 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë item_nameÏùò Í∞íÏù¥ Izze Îç∞Ïù¥ÌÑ∞Î•º Fizzy LizzyÎ°ú ÏàòÏ†ïÌïòÎùº

In [ ]:
df.loc[df['item_name'] == 'Izze', "item_name"] = "Fizzy Lizzy"

df.head()

order_id     quantity                              item_name  \
0            1            1           Chips and Fresh Tomato Salsa   
1  Fizzy Lizzy  Fizzy Lizzy                            Fizzy Lizzy   
2            1            1                       Nantucket Nectar   
3            1            1  Chips and Tomatillo-Green Chili Salsa   
4            2            2                           Chicken Bowl   

                                  choice_description   item_price    new_price  
0                                                NaN       $2.39          2.39  
1                                        Fizzy Lizzy  Fizzy Lizzy  Fizzy Lizzy  
2                                            [Apple]       $3.39          3.39  
3                                                NaN       $2.39          2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...      $16.98         16.98

Q37 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë choice_description Í∞íÏù¥ NaN Ïù∏ Îç∞Ïù¥ÌÑ∞Ïùò Í∞ØÏàòÎ•º Íµ¨ÌïòÏó¨Îùº

In [ ]:
len(df[df['choice_description'].isnull()])

1246

Q38 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë choice_description Í∞íÏù¥ NaN Ïù∏ Îç∞Ïù¥ÌÑ∞Î•º NoData Í∞íÏúºÎ°ú ÎåÄÏ≤¥ÌïòÎùº(loc Ïù¥Ïö©)

In [ ]:
df.loc[df.choice_description.isnull(),'choice_description'] ='NoData'

df.head()

order_id     quantity                              item_name  \
0            1            1           Chips and Fresh Tomato Salsa   
1  Fizzy Lizzy  Fizzy Lizzy                            Fizzy Lizzy   
2            1            1                       Nantucket Nectar   
3            1            1  Chips and Tomatillo-Green Chili Salsa   
4            2            2                           Chicken Bowl   

                                  choice_description   item_price    new_price  
0                                             NoData       $2.39          2.39  
1                                        Fizzy Lizzy  Fizzy Lizzy  Fizzy Lizzy  
2                                            [Apple]       $3.39          3.39  
3                                             NoData       $2.39          2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...      $16.98         16.98

Q39 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë choice_description Í∞íÏóê BlackÏù¥ Îì§Ïñ¥Í∞ÄÎäî Í≤ΩÏö∞Î•º Ïù∏Îç±Ïã±ÌïòÎùº

In [ ]:
df.loc[df.choice_description.str.contains("Black")]

order_id quantity             item_name  \
4           2        2          Chicken Bowl   
7           4        1         Steak Burrito   
9           5        1         Steak Burrito   
11          6        1  Chicken Crispy Tacos   
12          6        1    Chicken Soft Tacos   
...       ...      ...                   ...   
4604     1828        1          Chicken Bowl   
4608     1829        1        Veggie Burrito   
4611     1830        1        Veggie Burrito   
4612     1831        1         Carnitas Bowl   
4617     1833        1         Steak Burrito   

                                     choice_description item_price new_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98      16.98  
7     [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75      11.75  
9     [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25       9.25  
11    [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75       8.75  
12    [Roasted Chili Corn Salsa, [Rice, Black Beans,...     $8.75       8.75  
...                                                 ...        ...       ...  
4604  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...     $8.75       8.75  
4608  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.25      11.25  
4611  [Tomatillo Green Chili Salsa, [Rice, Fajita Ve...    $11.25      11.25  
4612  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $9.25       9.25  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75      11.75  

[1345 rows x 6 columns]

Q40 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë choice_description Í∞íÏóê Vegetables Îì§Ïñ¥Í∞ÄÏßÄ ÏïäÎäî Í≤ΩÏö∞Ïùò Í∞ØÏàòÎ•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
len(df.loc[~df.choice_description.str.contains("Vegetables")])

3900

Q41 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë item_name Í∞íÏù¥ NÏúºÎ°ú ÏãúÏûëÌïòÎäî Îç∞Ïù¥ÌÑ∞Î•º Î™®Îëê Ï∂îÏ∂úÌïòÎùº

In [ ]:
df.loc[df.item_name.str.startswith('N')]

order_id quantity         item_name         choice_description  \
2           1        1  Nantucket Nectar                    [Apple]   
22         11        1  Nantucket Nectar       [Pomegranate Cherry]   
105        46        1  Nantucket Nectar  [Pineapple Orange Banana]   
173        77        1  Nantucket Nectar                    [Apple]   
205        91        1  Nantucket Nectar             [Peach Orange]   
436       189        1  Nantucket Nectar       [Pomegranate Cherry]   
601       247        2  Nantucket Nectar  [Pineapple Orange Banana]   
925       381        1  Nantucket Nectar       [Pomegranate Cherry]   
1356      553        1  Nantucket Nectar       [Pomegranate Cherry]   
1585      641        1  Nantucket Nectar             [Peach Orange]   
1626      656        1  Nantucket Nectar  [Pineapple Orange Banana]   
1706      690        1  Nantucket Nectar                    [Apple]   
2162      872        1  Nantucket Nectar  [Pineapple Orange Banana]   
2379      947        2  Nantucket Nectar             [Peach Orange]   
2381      947        1  Nantucket Nectar                    [Apple]   
2430      965        1  Nantucket Nectar       [Pomegranate Cherry]   
2653     1053        1  Nantucket Nectar  [Pineapple Orange Banana]   
2818     1118        1  Nantucket Nectar                    [Apple]   
2838     1128        1  Nantucket Nectar             [Peach Orange]   
2853     1133        1  Nantucket Nectar                    [Apple]   
2949     1172        1  Nantucket Nectar             [Peach Orange]   
3318     1330        1  Nantucket Nectar             [Peach Orange]   
3368     1351        1  Nantucket Nectar  [Pineapple Orange Banana]   
3570     1433        1  Nantucket Nectar  [Pineapple Orange Banana]   
3845     1541        1  Nantucket Nectar             [Peach Orange]   
4019     1609        1  Nantucket Nectar  [Pineapple Orange Banana]   
4078     1632        1  Nantucket Nectar             [Peach Orange]   

     item_price new_price  
2        $3.39       3.39  
22       $3.39       3.39  
105      $3.39       3.39  
173      $3.39       3.39  
205      $3.39       3.39  
436      $3.39       3.39  
601      $6.78       6.78  
925      $3.39       3.39  
1356     $3.39       3.39  
1585     $3.39       3.39  
1626     $3.39       3.39  
1706     $3.39       3.39  
2162     $3.39       3.39  
2379     $6.78       6.78  
2381     $3.39       3.39  
2430     $3.39       3.39  
2653     $3.39       3.39  
2818     $3.39       3.39  
2838     $3.39       3.39  
2853     $3.39       3.39  
2949     $3.39       3.39  
3318     $3.39       3.39  
3368     $3.39       3.39  
3570     $3.39       3.39  
3845     $3.39       3.39  
4019     $3.39       3.39  
4078     $3.39       3.39

Q42 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë item_name Í∞íÏùò Îã®Ïñ¥Í∞ØÏàòÍ∞Ä 15Í∞ú Ïù¥ÏÉÅÏù∏ Îç∞Ïù¥ÌÑ∞Î•º Ïù∏Îç±Ïã±ÌïòÎùº

In [ ]:
df[df.item_name.str.len() >= 15]

order_id quantity                              item_name  \
0           1        1           Chips and Fresh Tomato Salsa   
2           1        1                       Nantucket Nectar   
3           1        1  Chips and Tomatillo-Green Chili Salsa   
8           4        1                       Steak Soft Tacos   
10          5        1                    Chips and Guacamole   
...       ...      ...                                    ...   
4615     1832        1                     Chicken Soft Tacos   
4616     1832        1                    Chips and Guacamole   
4619     1834        1                     Chicken Salad Bowl   
4620     1834        1                     Chicken Salad Bowl   
4621     1834        1                     Chicken Salad Bowl   

                                     choice_description item_price new_price  
0                                                NoData     $2.39       2.39  
2                                               [Apple]     $3.39       3.39  
3                                                NoData     $2.39       2.39  
8     [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25       9.25  
10                                               NoData     $4.45       4.45  
...                                                 ...        ...       ...  
4615   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]     $8.75       8.75  
4616                                             NoData     $4.45       4.45  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25      11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75       8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75       8.75  

[2373 rows x 6 columns]

Q43 dfÏùò Îç∞Ïù¥ÌÑ∞ Ï§ë new_priceÍ∞íÏù¥ lstÏóê Ìï¥ÎãπÌïòÎäî Í≤ΩÏö∞Ïùò Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏùÑ Íµ¨ÌïòÍ≥† Í∑∏ Í∞ØÏàòÎ•º Ï∂úÎ†•ÌïòÎùº lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]

In [ ]:
lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]

len(df[df['new_price'].isin(lst)])

1373

# 03_Grouping

In [ ]:
import pandas as pd


df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')

Q44 Îç∞Ïù¥ÌÑ∞Î•º Î°úÎìúÌïòÍ≥† ÏÉÅÏúÑ 5Í∞ú Ïª¨ÎüºÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.head(5)

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

Q45 Îç∞Ïù¥ÌÑ∞Ïùò Í∞Å host_nameÏùò ÎπàÎèÑÏàòÎ•º Íµ¨ÌïòÍ≥† host_nameÏúºÎ°ú Ï†ïÎ†¨ÌïòÏó¨ ÏÉÅÏúÑ 5Í∞úÎ•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.groupby('host_name').size().sort_index().head()

host_name
'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
dtype: int64

Q46 Îç∞Ïù¥ÌÑ∞Ïùò Í∞Å host_nameÏùò ÎπàÎèÑÏàòÎ•º Íµ¨ÌïòÍ≥† ÎπàÎèÑÏàò Í∏∞Ï§Ä ÎÇ¥Î¶ºÏ∞®Ïàú Ï†ïÎ†¨Ìïú Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏùÑ ÎßåÎì§Ïñ¥Îùº. ÎπàÎèÑÏàò Ïª¨ÎüºÏùÄ countsÎ°ú Î™ÖÎ™ÖÌïòÎùº


to_frame().rename(columns={0:'counts'})

In [ ]:
df.groupby('host_name').size().to_frame().rename(columns={0:'counts'}).sort_values('counts',ascending=False)

counts
host_name           
Michael          417
David            403
Sonder (NYC)     327
John             294
Alex             279
...              ...
ËØóÊúà                 1
Ëæ£Ëæ£                 1
ÊÄùÈì®                 1
ÊñáÊ∏Ö                 1
ÊñáÁ´ã                 1

[11452 rows x 1 columns]

Q47 neighbourhood_groupÏùò Í∞íÏóê Îî∞Î•∏ neighbourhoodÏª¨Îüº Í∞íÏùò Í∞ØÏàòÎ•º Íµ¨ÌïòÏó¨Îùº

In [ ]:
df.groupby(['neighbourhood_group','neighbourhood']).size()

neighbourhood_group  neighbourhood
Bronx                Allerton         42
                     Baychester        7
                     Belmont          24
                     Bronxdale        19
                     Castle Hill       9
                                      ..
Staten Island        Tottenville       7
                     West Brighton    18
                     Westerleigh       2
                     Willowbrook       1
                     Woodrow           1
Length: 221, dtype: int64

In [ ]:
df.groupby(['neighbourhood_group','neighbourhood'], as_index=False).size()

neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

Q48 neighbourhood_groupÏùò Í∞íÏóê Îî∞Î•∏ neighbourhoodÏª¨Îüº Í∞í Ï§ë neighbourhood_groupÍ∑∏Î£πÏùò ÏµúÎåìÍ∞íÎì§ÏùÑ Ï∂úÎ†•ÌïòÎùº

In [ ]:
df.groupby(['neighbourhood_group','neighbourhood']).size().groupby('neighbourhood_group').max()

neighbourhood_group
Bronx              70
Brooklyn         3920
Manhattan        2658
Queens            900
Staten Island      48
dtype: int64

Q49 neighbourhood_group Í∞íÏóê Îî∞Î•∏ priceÍ∞íÏùò ÌèâÍ∑†, Î∂ÑÏÇ∞, ÏµúÎåÄ, ÏµúÏÜå Í∞íÏùÑ Íµ¨ÌïòÏó¨Îùº üîë

In [ ]:
df.groupby('neighbourhood_group').price.agg(['mean','var','max','min'])

mean           var    max  min
neighbourhood_group                                      
Bronx                 87.496792  11386.885081   2500    0
Brooklyn             124.383207  34921.719135  10000    0
Manhattan            196.875814  84904.159185  10000    0
Queens                99.517649  27923.130227  10000   10
Staten Island        114.812332  77073.088342   5000   13

Q50 neighbourhood_group Í∞íÏóê Îî∞Î•∏ reviews_per_month ÌèâÍ∑†, Î∂ÑÏÇ∞, ÏµúÎåÄ, ÏµúÏÜå Í∞íÏùÑ Íµ¨ÌïòÏó¨Îùº

In [ ]:
df.groupby('neighbourhood_group').reviews_per_month.agg(['mean','var','max','min'])

mean       var    max   min
neighbourhood_group                                 
Bronx                1.837831  2.799878  10.34  0.02
Brooklyn             1.283212  2.299040  14.00  0.01
Manhattan            1.272131  2.651206  58.50  0.01
Queens               1.941200  4.897848  20.94  0.01
Staten Island        1.872580  2.840895  10.12  0.02

Q51 neighbourhood Í∞íÍ≥º neighbourhood_group Í∞íÏóê Îî∞Î•∏ price Ïùò ÌèâÍ∑†ÏùÑ Íµ¨ÌïòÎùº

In [ ]:
df.groupby(['neighbourhood','neighbourhood_group']).price.mean()

neighbourhood    neighbourhood_group
Allerton         Bronx                   87.595238
Arden Heights    Staten Island           67.250000
Arrochar         Staten Island          115.000000
Arverne          Queens                 171.779221
Astoria          Queens                 117.187778
                                           ...    
Windsor Terrace  Brooklyn               138.993631
Woodhaven        Queens                  67.170455
Woodlawn         Bronx                   60.090909
Woodrow          Staten Island          700.000000
Woodside         Queens                  85.097872
Name: price, Length: 221, dtype: float64

Q52 neighbourhood Í∞íÍ≥º neighbourhood_group Í∞íÏóê Îî∞Î•∏ price Ïùò ÌèâÍ∑†ÏùÑ Í≥ÑÏ∏µÏ†Å indexing ÏóÜÏù¥ Íµ¨ÌïòÎùº

unstack

In [ ]:
df.groupby(['neighbourhood','neighbourhood_group']).price.mean().unstack()

neighbourhood_group      Bronx    Brooklyn  Manhattan      Queens  \
neighbourhood                                                       
Allerton             87.595238         NaN        NaN         NaN   
Arden Heights              NaN         NaN        NaN         NaN   
Arrochar                   NaN         NaN        NaN         NaN   
Arverne                    NaN         NaN        NaN  171.779221   
Astoria                    NaN         NaN        NaN  117.187778   
...                        ...         ...        ...         ...   
Windsor Terrace            NaN  138.993631        NaN         NaN   
Woodhaven                  NaN         NaN        NaN   67.170455   
Woodlawn             60.090909         NaN        NaN         NaN   
Woodrow                    NaN         NaN        NaN         NaN   
Woodside                   NaN         NaN        NaN   85.097872   

neighbourhood_group  Staten Island  
neighbourhood                       
Allerton                       NaN  
Arden Heights                67.25  
Arrochar                    115.00  
Arverne                        NaN  
Astoria                        NaN  
...                            ...  
Windsor Terrace                NaN  
Woodhaven                      NaN  
Woodlawn                       NaN  
Woodrow                     700.00  
Woodside                       NaN  

[221 rows x 5 columns]

Q53 neighbourhood Í∞íÍ≥º neighbourhood_group Í∞íÏóê Îî∞Î•∏ price Ïùò ÌèâÍ∑†ÏùÑ Í≥ÑÏ∏µÏ†Å indexing ÏóÜÏù¥ Íµ¨ÌïòÍ≥† nan Í∞íÏùÄ -999Í∞íÏúºÎ°ú Ï±ÑÏõåÎùº

In [ ]:
df.groupby(['neighbourhood','neighbourhood_group']).price.mean().unstack().fillna(-999)

neighbourhood_group       Bronx    Brooklyn  Manhattan      Queens  \
neighbourhood                                                        
Allerton              87.595238 -999.000000     -999.0 -999.000000   
Arden Heights       -999.000000 -999.000000     -999.0 -999.000000   
Arrochar            -999.000000 -999.000000     -999.0 -999.000000   
Arverne             -999.000000 -999.000000     -999.0  171.779221   
Astoria             -999.000000 -999.000000     -999.0  117.187778   
...                         ...         ...        ...         ...   
Windsor Terrace     -999.000000  138.993631     -999.0 -999.000000   
Woodhaven           -999.000000 -999.000000     -999.0   67.170455   
Woodlawn              60.090909 -999.000000     -999.0 -999.000000   
Woodrow             -999.000000 -999.000000     -999.0 -999.000000   
Woodside            -999.000000 -999.000000     -999.0   85.097872   

neighbourhood_group  Staten Island  
neighbourhood                       
Allerton                   -999.00  
Arden Heights                67.25  
Arrochar                    115.00  
Arverne                    -999.00  
Astoria                    -999.00  
...                            ...  
Windsor Terrace            -999.00  
Woodhaven                  -999.00  
Woodlawn                   -999.00  
Woodrow                     700.00  
Woodside                   -999.00  

[221 rows x 5 columns]

Q54 Îç∞Ïù¥ÌÑ∞Ï§ë neighbourhood_group Í∞íÏù¥ QueensÍ∞íÏùÑ Í∞ÄÏßÄÎäî Îç∞Ïù¥ÌÑ∞Îì§ Ï§ë neighbourhood Í∑∏Î£πÎ≥ÑÎ°ú priceÍ∞íÏùò ÌèâÍ∑†, Î∂ÑÏÇ∞, ÏµúÎåÄ, ÏµúÏÜåÍ∞íÏùÑ Íµ¨ÌïòÎùº

In [ ]:
df[df['neighbourhood_group'] =='Queens'].groupby("neighbourhood").price.agg(['mean','var','max','min'])

mean            var    max  min
neighbourhood                                             
Arverne              171.779221   37383.411141   1500   35
Astoria              117.187778  122428.811196  10000   25
Bay Terrace          142.000000    6816.400000    258   32
Bayside              157.948718  166106.470985   2600   30
Bayswater             87.470588    2330.889706    230   45
Belle Harbor         171.500000    8226.571429    350   85
Bellerose             99.357143    3093.016484    240   42
Breezy Point         213.333333    1008.333333    250  195
Briarwood            105.875000   18503.165909   1000   30
Cambria Heights       81.730769    2960.604615    250   31
College Point         88.000000    6445.555556    400   44
Corona                59.171875    2430.557292    359   23
Ditmars Steinway      95.029126    4214.112785    600   22
Douglaston            82.750000    2347.071429    178   40
East Elmhurst         81.183784    4369.487779    700   16
Edgemere              94.727273    4219.418182    200   40
Elmhurst              80.459916    3896.563005    443   15
Far Rockaway         165.862069   52575.980296    900   35
Flushing              93.514085   12417.177448   1500   15
Forest Hills         121.625000   44533.368881   2350   16
Fresh Meadows         99.500000    6394.451613    375   39
Glendale              90.796296    3230.882250    299   25
Hollis                88.642857    1483.016484    175   50
Holliswood           135.750000    5091.583333    239   79
Howard Beach         115.400000    4241.936842    250   40
Jackson Heights       80.897849    2150.470590    260   23
Jamaica               95.770563    8067.047130   1000   10
Jamaica Estates      182.947368   29006.052632    750   35
Jamaica Hills        132.125000   11304.696429    325   50
Kew Gardens           88.375000    2632.306452    219   35
Kew Gardens Hills    112.307692    6230.621538    399   40
Laurelton             95.333333    4355.529412    254   34
Little Neck           75.200000    2368.700000    149   32
Long Island City     127.465549   15529.503009   2000   30
Maspeth               83.645455    2223.607089    245   11
Middle Village       109.580645    3537.118280    265   28
Neponsit             274.666667    5625.333333    350  200
Ozone Park            85.274194    1705.415389    200   25
Queens Village        83.933333    2386.470056    320   25
Rego Park             83.877358    3659.003863    300   21
Richmond Hill         87.117021    3474.147449    300   28
Ridgewood             77.184397    2629.311889    375   20
Rockaway Beach       132.178571    6254.622078    545   49
Rosedale              76.694915    2963.939801    350   22
South Ozone Park      82.400000    4619.989744    400   29
Springfield Gardens   94.235294    2490.848739    300   40
St. Albans           100.828947    9489.903684    600   25
Sunnyside             84.865014    2727.746922    600   12
Whitestone           107.545455   13632.072727    400   35
Woodhaven             67.170455    1642.464864    250   10
Woodside              85.097872    5001.900636    500   28

Q55 Îç∞Ïù¥ÌÑ∞Ï§ë neighbourhood_group Í∞íÏóê Îî∞Î•∏ room_type Ïª¨ÎüºÏùò Ïà´ÏûêÎ•º Íµ¨ÌïòÍ≥† neighbourhood_group Í∞íÏùÑ Í∏∞Ï§ÄÏúºÎ°ú Í∞Å Í∞íÏùò ÎπÑÏú®ÏùÑ Íµ¨ÌïòÏó¨Îùº (Ïò§Îãµ)

In [ ]:
# df.groupby(['neighbourhood_group', 'room_type']).size().unstack()

result = df[['neighbourhood_group','room_type']].groupby(['neighbourhood_group','room_type']).size().unstack()
result.loc[:,:] = (result.values / result.sum(axis=1).values.reshape(-1,1))
result


<ipython-input-218-517339b8317b>:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.34738772 0.47547752 0.60934398 0.36992587 0.47184987]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  result.loc[:,:] = (result.values / result.sum(axis=1).values.reshape(-1,1))
<ipython-input-218-517339b8317b>:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.59761687 0.50397931 0.36849638 0.59512884 0.50402145]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  result.loc[:,:] = (result.values / result.sum(axis=1).values.reshape(-1,1))
<ipython-input-218-517339b8317b>:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.05499542 0.02054318 0.02215964 0.03494529 0.02412869]' has dtype incompatible with int64,

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group                                            
Bronx                       0.347388      0.597617     0.054995
Brooklyn                    0.475478      0.503979     0.020543
Manhattan                   0.609344      0.368496     0.022160
Queens                      0.369926      0.595129     0.034945
Staten Island               0.471850      0.504021     0.024129

# 04_Apply , Map

In [ ]:
import pandas as pd

Q56 Îç∞Ïù¥ÌÑ∞Î•º Î°úÎìúÌïòÍ≥† Îç∞Ïù¥ÌÑ∞ ÌñâÍ≥º Ïó¥Ïùò Í∞ØÏàòÎ•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv')

df.shape

print("Ìñâ: ", df.shape[0])
print("Ïó¥: ", df.shape[1])

print(df.shape)

Ìñâ:  10127
Ïó¥:  19
(10127, 19)


Q57 Income_CategoryÏùò Ïπ¥ÌÖåÍ≥†Î¶¨Î•º map Ìï®ÏàòÎ•º Ïù¥Ïö©ÌïòÏó¨ Îã§ÏùåÍ≥º Í∞ôÏù¥ Î≥ÄÍ≤ΩÌïòÏó¨ newIncome Ïª¨ÎüºÏóê Îß§ÌïëÌïòÎùº

Unknown : N

Less than $40K : a

$40K - $60K : b

$60K - $80K : c

$80K - $120K : d

$120K +‚Äô : e

In [ ]:
dic = {
    'Unknown'        : 'N',
    'Less than $40K' : 'a',
    '$40K - $60K'    : 'b',
    '$60K - $80K'    : 'c',
    '$80K - $120K'   : 'd',
    '$120K +'        : 'e'
}

df['newIncome']  =df.Income_Category.map(lambda x: dic[x])

df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

Q58 Income_CategoryÏùò Ïπ¥ÌÖåÍ≥†Î¶¨Î•º apply Ìï®ÏàòÎ•º Ïù¥Ïö©ÌïòÏó¨ Îã§ÏùåÍ≥º Í∞ôÏù¥ Î≥ÄÍ≤ΩÌïòÏó¨ newIncome Ïª¨ÎüºÏóê Îß§ÌïëÌïòÎùº

In [ ]:
def func(x):
  if x == "Unknown":
    return "N"
  elif x == 'Less than $40K':
    return "a"
  elif x == '$40K - $60K':
    return "b"
  elif x == '$60K - $80K':
    return "c"
  elif x == '$80K - $120K':
    return 'd'
  elif x == '$120K +':
    return 'e'

df['newIncome'] = df.Income_Category.apply(func)

df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

Q59 Customer_AgeÏùò Í∞íÏùÑ Ïù¥Ïö©ÌïòÏó¨ ÎÇòÏù¥ Íµ¨Í∞ÑÏùÑ AgeState Ïª¨ÎüºÏúºÎ°ú Ï†ïÏùòÌïòÎùº. (0~9 : 0 , 10~19 :10 , 20~29 :20 ‚Ä¶ Í∞Å Íµ¨Í∞ÑÏùò ÎπàÎèÑÏàòÎ•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
df['Customer_Age']

def func(x):
  return x // 10

df['AgeState'] = df['Customer_Age'].apply(func)

df.groupby('AgeState').size()

AgeState
2     195
3    1841
4    4561
5    2998
6     530
7       2
dtype: int64

Q60 Education_LevelÏùò Í∞íÏ§ë GraduateÎã®Ïñ¥Í∞Ä Ìè¨Ìï®ÎêòÎäî Í∞íÏùÄ 1 Í∑∏Î†áÏßÄ ÏïäÏùÄ Í≤ΩÏö∞ÏóêÎäî 0ÏúºÎ°ú Î≥ÄÍ≤ΩÌïòÏó¨ newEduLevel Ïª¨ÎüºÏùÑ Ï†ïÏùòÌïòÍ≥† ÎπàÎèÑÏàòÎ•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
def func(x):
  if "Graduate" in x:
    return 1
  else:
    return 0

df['newEduLevel'] = df['Education_Level'].apply(func)

df.groupby('newEduLevel').size()

newEduLevel
0    6483
1    3644
dtype: int64

Q61 Credit_Limit Ïª¨ÎüºÍ∞íÏù¥ 4500 Ïù¥ÏÉÅÏù∏ Í≤ΩÏö∞ 1 Í∑∏Ïô∏Ïùò Í≤ΩÏö∞ÏóêÎäî Î™®Îëê 0ÏúºÎ°ú ÌïòÎäî newLimit Ï†ïÏùòÌïòÎùº. newLimit Í∞Å Í∞íÎì§Ïùò ÎπàÎèÑÏàòÎ•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
def func(x):
  if x >= 4500:
    return 1
  else:
    return 0

df['newLimit'] = df["Credit_Limit"].apply(func)

df.groupby('newLimit').size()
df['newLimit'].value_counts()

newLimit
1    5096
0    5031
Name: count, dtype: int64

Q62 Marital_Status Ïª¨ÎüºÍ∞íÏù¥ Married Ïù¥Í≥† Card_Category Ïª¨ÎüºÏùò Í∞íÏù¥ PlatinumÏù∏ Í≤ΩÏö∞ 1 Í∑∏Ïô∏Ïùò Í≤ΩÏö∞ÏóêÎäî Î™®Îëê 0ÏúºÎ°ú ÌïòÎäî newStateÏª¨ÎüºÏùÑ Ï†ïÏùòÌïòÎùº. newStateÏùò Í∞Å Í∞íÎì§Ïùò ÎπàÎèÑÏàòÎ•º Ï∂úÎ†•ÌïòÎùº

In [ ]:
def func(x):
  if x.Marital_Status == 'Married' and x.Card_Category == 'Platinum':
    return 1
  else:
    return 0

df['newState'] = df.apply(func, axis = 1)

df['newState'].value_counts()

newState
0    10120
1        7
Name: count, dtype: int64

Q63 Gender Ïª¨ÎüºÍ∞í MÏù∏ Í≤ΩÏö∞ male FÏù∏ Í≤ΩÏö∞ femaleÎ°ú Í∞íÏùÑ Î≥ÄÍ≤ΩÌïòÏó¨ Gender Ïª¨ÎüºÏóê ÏÉàÎ°≠Í≤å Ï†ïÏùòÌïòÎùº. Í∞Å valueÏùò ÎπàÎèÑÎ•º Ï∂úÎ†•ÌïòÎùº



In [ ]:
def func(x):
  if x == "M":
    return "male"
  elif x == "F":
    return "female"

df['Gender'] = df.Gender.apply(func)
df['Gender'].value_counts()

Gender
female    5358
male      4769
Name: count, dtype: int64

# 05_Time_Series

In [ ]:
import pandas as pd

Q64 Îç∞Ïù¥ÌÑ∞Î•º Î°úÎìúÌïòÍ≥† Í∞Å Ïó¥Ïùò Îç∞Ïù¥ÌÑ∞ ÌÉÄÏûÖÏùÑ ÌååÏïÖÌïòÎùº

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Yr_Mo_Dy  6574 non-null   object 
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: float64(12), object(1)
memory usage: 667.8+ KB


Q65 Yr_Mo_DyÏùÑ ÌåêÎã§Ïä§ÏóêÏÑú Ïù∏ÏãùÌï† Ïàò ÏûàÎäî datetime64ÌÉÄÏûÖÏúºÎ°ú Î≥ÄÍ≤ΩÌïòÎùº

In [ ]:
df.Yr_Mo_Dy = pd.to_datetime(df.Yr_Mo_Dy)
df.Yr_Mo_Dy

0      2061-01-01
1      2061-01-02
2      2061-01-03
3      2061-01-04
4      2061-01-05
          ...    
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

Q66 Yr_Mo_DyÏóê Ï°¥Ïû¨ÌïòÎäî ÎÖÑÎèÑÏùò Ïú†ÏùºÍ∞íÏùÑ Î™®Îëê Ï∂úÎ†•ÌïòÎùº

In [ ]:
df['Yr_Mo_Dy'].dt.year.unique()

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978], dtype=int32)

Q67 Yr_Mo_DyÏóê ÎÖÑÎèÑÍ∞Ä 2061ÎÖÑ Ïù¥ÏÉÅÏùò Í≤ΩÏö∞ÏóêÎäî Î™®Îëê ÏûòÎ™ªÎêú Îç∞Ïù¥ÌÑ∞Ïù¥Îã§. Ìï¥ÎãπÍ≤ΩÏö∞Ïùò Í∞íÏùÄ 100ÏùÑ ÎπºÏÑú ÏÉàÎ°≠Í≤å ÎÇ†ÏßúÎ•º Yr_Mo_Dy Ïª¨ÎüºÏóê Ï†ïÏùòÌïòÎùº(Ïò§Îãµ)



In [ ]:
def fix_century(x):
    import datetime

    year = x.year - 100 if x.year >= 2061 else x.year
    return pd.to_datetime(datetime.date(year, x.month, x.day))


df['Yr_Mo_Dy'] = df['Yr_Mo_Dy'].apply(fix_century)


df.head()

Yr_Mo_Dy    RPT    VAL    ROS    KIL    SHA   BIR    DUB    CLA    MUL  \
0 1961-01-01  15.04  14.96  13.17   9.29    NaN  9.87  13.67  10.25  10.83   
1 1961-01-02  14.71    NaN  10.83   6.50  12.62  7.67  11.50  10.04   9.79   
2 1961-01-03  18.50  16.88  12.33  10.13  11.17  6.17  11.25    NaN   8.50   
3 1961-01-04  10.58   6.63  11.75   4.58   4.54  2.88   8.63   1.79   5.83   
4 1961-01-05  13.33  13.25  11.42   6.17  10.71  8.21  11.92   6.54  10.92   

     CLO    BEL    MAL  
0  12.58  18.50  15.04  
1   9.67  17.54  13.83  
2   7.67  12.75  12.71  
3   5.88   5.46  10.88  
4  10.34  12.92  11.83

Q68 ÎÖÑÎèÑÎ≥Ñ Í∞ÅÏª¨ÎüºÏùò ÌèâÍ∑†Í∞íÏùÑ Íµ¨ÌïòÏó¨Îùº

In [ ]:
df.head(2)

Yr_Mo_Dy    RPT    VAL    ROS   KIL    SHA   BIR    DUB    CLA    MUL  \
0 1961-01-01  15.04  14.96  13.17  9.29    NaN  9.87  13.67  10.25  10.83   
1 1961-01-02  14.71    NaN  10.83  6.50  12.62  7.67  11.50  10.04   9.79   

     CLO    BEL    MAL  
0  12.58  18.50  15.04  
1   9.67  17.54  13.83

In [ ]:
df.groupby(df['Yr_Mo_Dy'].dt.year).mean()

Yr_Mo_Dy        RPT        VAL        ROS       KIL  \
Yr_Mo_Dy                                                                  
1961     1961-07-02 00:00:00  12.299583  10.351796  11.362369  6.958227   
1962     1962-07-02 00:00:00  12.246923  10.110438  11.732712  6.960440   
1963     1963-07-02 00:00:00  12.813452  10.836986  12.541151  7.330055   
1964     1964-07-01 12:00:00  12.363661  10.920164  12.104372  6.787787   
1965     1965-07-02 00:00:00  12.451370  11.075534  11.848767  6.858466   
1966     1966-07-02 00:00:00  13.461973  11.557205  12.020630  7.345726   
1967     1967-07-02 00:00:00  12.737151  10.990986  11.739397  7.143425   
1968     1968-07-01 12:00:00  11.835628  10.468197  11.409754  6.477678   
1969     1969-07-02 00:00:00  11.166356   9.723699  10.902000  5.767973   
1970     1970-07-02 00:00:00  12.600329  10.726932  11.730247  6.217178   
1971     1971-07-02 00:00:00  11.273123   9.095178  11.088329  5.241507   
1972     1972-07-01 12:00:00  12.463962  10.561311  12.058333  5.929699   
1973     1973-07-02 00:00:00  11.828466  10.680493  10.680493  5.547863   
1974     1974-07-02 00:00:00  13.643096  11.811781  12.336356  6.427041   
1975     1975-07-02 00:00:00  12.008575  10.293836  11.564712  5.269096   
1976     1976-07-01 12:00:00  11.737842  10.203115  10.761230  5.109426   
1977     1977-07-02 00:00:00  13.099616  11.144493  12.627836  6.073945   
1978     1978-07-02 00:00:00  12.504356  11.044274  11.380000  6.082356   

                SHA       BIR        DUB        CLA       MUL        CLO  \
Yr_Mo_Dy                                                                   
1961      10.881763  7.729726   9.733923   8.858788  8.647652   9.835577   
1962      10.657918  7.393068  11.020712   8.793753  8.316822   9.676247   
1963      11.724110  8.434712  11.075699  10.336548  8.903589  10.224438   
1964      11.454481  7.570874  10.259153   9.467350  7.789016  10.207951   
1965      11.024795  7.478110  10.618712   8.879918  7.907425   9.918082   
1966      11.805041  7.793671  10.579808   8.835096  8.514438   9.768959   
1967      11.630740  7.368164  10.652027   9.325616  8.645014   9.547425   
1968      10.760765  6.067322   8.859180   8.255519  7.224945   7.832978   
1969       9.873918  6.189973   8.564493   7.711397  7.924521   7.754384   
1970      10.567370  7.609452   9.609890   8.334630  9.297616   8.289808   
1971       9.440329  6.097151   8.385890   6.757315  7.915370   7.229753   
1972       9.430410  6.358825   9.704508   7.680792  8.357295   7.515273   
1973       9.640877  6.548740   8.482110   7.614274  8.245534   7.812411   
1974      11.110986  6.809781  10.084603   9.896986  9.331753   8.736356   
1975       9.190082  5.668521   8.562603   7.843836  8.797945   7.382822   
1976       8.846339  6.311038   9.149126   7.146202  8.883716   7.883087   
1977      10.003836  8.586438  11.523205   8.378384  9.098192   8.821616   
1978      10.167233  7.650658   9.489342   8.800466  9.089753   8.301699   

                BEL        MAL  
Yr_Mo_Dy                        
1961      13.502795  13.680773  
1962      12.930685  14.323956  
1963      13.638877  14.999014  
1964      13.740546  14.910301  
1965      12.964247  15.591644  
1966      14.265836  16.307260  
1967      14.774548  17.135945  
1968      12.808634  15.017486  
1969      12.621233  15.762904  
1970      13.183644  16.456027  
1971      12.208932  15.025233  
1972      12.727377  15.028716  
1973      12.169699  15.441096  
1974      13.252959  16.947671  
1975      12.631671  15.307863  
1976      12.332377  15.471448  
1977      13.459068  16.590849  
1978      12.967397  16.771370

Q69 weekdayÏª¨ÎüºÏùÑ ÎßåÎì§Í≥† ÏöîÏùºÎ≥ÑÎ°ú Îß§ÌïëÌïòÎùº ( ÏõîÏöîÏùº: 0 ~ ÏùºÏöîÏùº :6)

In [ ]:
df['weekday'] = df['Yr_Mo_Dy'].dt.weekday
df['weekday']

0       6
1       0
2       1
3       2
4       3
       ..
6569    2
6570    3
6571    4
6572    5
6573    6
Name: weekday, Length: 6574, dtype: int32

Q70 weekdayÏª¨ÎüºÏùÑ Í∏∞Ï§ÄÏúºÎ°ú Ï£ºÎßêÏù¥Î©¥ 1 ÌèâÏùºÏù¥Î©¥ 0Ïùò Í∞íÏùÑ Í∞ÄÏßÄÎäî WeekCheck Ïª¨ÎüºÏùÑ ÎßåÎì§Ïñ¥Îùº

In [ ]:
def func(x):
  if x >= 5:
    return 1
  else:
    return 0

df['WeekCheck'] = df.weekday.apply(func)

df['WeekCheck']

0       1
1       0
2       0
3       0
4       0
       ..
6569    0
6570    0
6571    0
6572    1
6573    1
Name: WeekCheck, Length: 6574, dtype: int64

Q71 ÎÖÑÎèÑ, ÏùºÏûê ÏÉÅÍ¥ÄÏóÜÏù¥ Î™®Îì† Ïª¨ÎüºÏùò Í∞Å Îã¨Ïùò ÌèâÍ∑†ÏùÑ Íµ¨ÌïòÏó¨Îùº

In [ ]:
df.groupby(df['Yr_Mo_Dy'].dt.month).mean()

Yr_Mo_Dy        RPT        VAL        ROS  \
Yr_Mo_Dy                                                                  
1        1969-07-17 06:40:00.000000000  14.847325  12.914560  13.299624   
2        1969-08-17 07:50:33.070866142  13.710906  12.111122  12.879132   
3        1969-09-14 12:00:00.000000000  13.158687  11.505842  12.648118   
4        1969-10-15 00:00:00.000000000  12.555648  10.429759  12.204815   
5        1969-11-14 12:00:00.000000000  11.724032  10.145619  11.550394   
6        1969-12-15 00:00:00.000000000  10.451317   8.949704  10.361315   
7        1970-01-14 12:00:00.000000000   9.992007   8.357778   9.349642   
8        1970-02-14 12:00:00.000000000  10.213411   8.415143   9.993441   
9        1970-03-17 00:00:00.000000000  11.458519   9.981002  10.756883   
10       1970-04-16 12:00:00.000000000  12.660610  11.010681  11.453943   
11       1970-05-17 00:00:00.000000000  13.200722  11.639500  12.293407   
12       1970-06-16 12:00:00.000000000  14.446398  12.353602  13.212276   

               KIL        SHA       BIR        DUB       CLA       MUL  \
Yr_Mo_Dy                                                                 
1         7.199498  11.667734  8.054839  11.819355  9.512047  9.543208   
2         6.942411  11.551772  7.633858  11.206024  9.341437  9.313169   
3         7.265907  11.554516  7.959409  11.310179  9.635896  9.700324   
4         6.898037  10.677667  7.441389  10.221315  8.909056  8.930870   
5         6.307487  10.224301  6.942061   8.797738  8.452903  8.040806   
6         5.652278   9.529926  6.410093   8.009556  7.920796  7.639796   
7         5.416935   9.302634  5.972348   7.843501  7.262760  7.544480   
8         5.270681   8.901559  5.891057   7.772312  6.842025  7.240573   
9         5.615176   9.766315  6.566222   8.609722  7.745677  7.610556   
10        6.065215  10.550251  7.159910   9.387778  8.726308  8.347181   
11        6.247611  10.501130  7.134333  10.814861  8.427167  8.604000   
12        6.829910  11.301254  7.963710  11.849050  9.209355  9.447258   

                CLO        BEL        MAL   weekday  WeekCheck  \
Yr_Mo_Dy                                                         
1         10.053566  14.550520  18.028763  2.989247   0.284946   
2          9.518051  13.728898  17.156142  3.005906   0.287402   
3         10.096953  13.810609  16.909317  3.000000   0.283154   
4          9.158019  12.664759  14.937611  3.011111   0.288889   
5          8.524857  12.767258  13.736039  2.982079   0.283154   
6          7.729185  12.246407  12.861818  3.007407   0.285185   
7          7.321416  11.676505  12.800789  3.001792   0.288530   
8          7.002783  11.110090  12.565943  2.991039   0.283154   
9          7.689278  12.686389  14.761963  3.009259   0.287037   
10         8.850376  14.155323  16.697151  2.998208   0.286738   
11         8.943167  13.815741  18.114185  2.992593   0.283333   
12         9.627670  14.259516  18.697599  3.017921   0.288530   

                                 month  
Yr_Mo_Dy                                
1        1969-07-17 06:40:00.000000000  
2        1969-08-17 07:50:33.070866142  
3        1969-09-14 12:00:00.000000000  
4        1969-10-15 00:00:00.000000000  
5        1969-11-14 12:00:00.000000000  
6        1969-12-15 00:00:00.000000000  
7        1970-01-14 12:00:00.000000000  
8        1970-02-14 12:00:00.000000000  
9        1970-03-17 00:00:00.000000000  
10       1970-04-16 12:00:00.000000000  
11       1970-05-17 00:00:00.000000000  
12       1970-06-16 12:00:00.000000000

Q72 Î™®Îì† Í≤∞Ï∏°ÏπòÎäî Ïª¨ÎüºÍ∏∞Ï§Ä ÏßÅÏ†ÑÏùò Í∞íÏúºÎ°ú ÎåÄÏ≤¥ÌïòÍ≥† Ï≤´Î≤àÏß∏ ÌñâÏóê Í≤∞Ï∏°ÏπòÍ∞Ä ÏûàÏùÑÍ≤ΩÏö∞ Îí§ÏóêÏûàÎäî Í∞íÏúºÎ°ú ÎåÄÏ±ÑÌïòÎùº

In [ ]:
df = df.fillna(method='ffill').fillna(method='bfill')

df.isnull().sum()

<ipython-input-302-f2145b59ef6b>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill').fillna(method='bfill')


Yr_Mo_Dy     0
RPT          0
VAL          0
ROS          0
KIL          0
SHA          0
BIR          0
DUB          0
CLA          0
MUL          0
CLO          0
BEL          0
MAL          0
weekday      0
WeekCheck    0
month        0
dtype: int64

Q73 ÎÖÑÎèÑ - ÏõîÏùÑ Í∏∞Ï§ÄÏúºÎ°ú Î™®Îì† Ïª¨ÎüºÏùò ÌèâÍ∑†Í∞íÏùÑ Íµ¨ÌïòÏó¨Îùº (Ïò§Îãµ)

In [ ]:
df.groupby(df['Yr_Mo_Dy'].dt.to_period('M')).mean()

Yr_Mo_Dy        RPT        VAL        ROS       KIL  \
Yr_Mo_Dy                                                                  
1961-01  1961-01-16 00:00:00  14.932581  12.084194  13.431613  7.736774   
1961-02  1961-02-14 12:00:00  16.269286  14.975357  14.324643  9.116786   
1961-03  1961-03-16 00:00:00  11.015806  11.296452  10.752903  7.137742   
1961-04  1961-04-15 12:00:00  10.722667   9.427667   9.998000  5.830667   
1961-05  1961-05-16 00:00:00   9.860968   8.735161  10.818065  5.892258   
...                      ...        ...        ...        ...       ...   
1978-08  1978-08-16 00:00:00   9.645161   8.259355   9.032258  4.502903   
1978-09  1978-09-15 12:00:00  10.913667  10.895000  10.635000  5.725000   
1978-10  1978-10-16 00:00:00   9.897742   8.670968   9.295806  4.721290   
1978-11  1978-11-15 12:00:00  16.151667  14.802667  13.508000  7.317333   
1978-12  1978-12-16 00:00:00  16.175484  13.748065  15.635161  7.094839   

                SHA        BIR        DUB        CLA        MUL        CLO  \
Yr_Mo_Dy                                                                     
1961-01   11.215806   8.588065  11.184839   9.270968   9.085806  10.107419   
1961-02   13.852143  10.937500  11.890714  11.846071  11.821429  12.714286   
1961-03   10.509355   8.866774   9.644194   9.829677  10.646129  11.251935   
1961-04    8.435000   6.495000   6.925333   7.094667   7.342333   7.237000   
1961-05    9.490323   6.574839   7.477097   8.177097   8.039355   8.499355   
...             ...        ...        ...        ...        ...        ...   
1978-08    7.368065   5.935161   5.650323   5.417742   7.241290   5.536774   
1978-09   10.372000   9.278333  10.790333   9.583000  10.069333   8.939000   
1978-10    8.525161   6.774194   8.115484   7.337742   8.297742   8.243871   
1978-11   11.475000   8.743000  11.492333   9.657333  10.701333  10.676000   
1978-12   11.398710   9.241613  12.077419  10.194839  10.616774  11.028710   

                BEL        MAL   weekday  WeekCheck               month  
Yr_Mo_Dy                                                                 
1961-01   13.880968  14.703226  2.935484   0.290323 1961-01-16 00:00:00  
1961-02   18.583214  15.411786  3.000000   0.285714 1961-02-14 12:00:00  
1961-03   16.410968  15.637742  3.000000   0.258065 1961-03-16 00:00:00  
1961-04   11.147333  10.278333  3.166667   0.333333 1961-04-15 12:00:00  
1961-05   11.900323  12.011613  2.806452   0.258065 1961-05-16 00:00:00  
...             ...        ...       ...        ...                 ...  
1978-08   10.466774  12.054194  2.903226   0.258065 1978-08-16 00:00:00  
1978-09   15.680333  19.391333  3.100000   0.300000 1978-09-15 12:00:00  
1978-10   13.776774  17.150000  2.935484   0.290323 1978-10-16 00:00:00  
1978-11   17.404667  20.723000  2.966667   0.266667 1978-11-15 12:00:00  
1978-12   13.859677  21.371613  3.193548   0.322581 1978-12-16 00:00:00  

[216 rows x 16 columns]

Q74 RPT Ïª¨ÎüºÏùò Í∞íÏùÑ ÏùºÏûêÎ≥Ñ Í∏∞Ï§ÄÏúºÎ°ú 1Ï∞®Ï∞®Î∂ÑÌïòÎùº

In [ ]:
df['RPT'].diff()

0        NaN
1      -0.33
2       3.79
3      -7.92
4       2.75
        ... 
6569    3.75
6570   -4.37
6571    0.79
6572    4.50
6573    1.83
Name: RPT, Length: 6574, dtype: float64

Q75 RPTÏôÄ VALÏùò Ïª¨ÎüºÏùÑ ÏùºÏ£ºÏùº Í∞ÑÍ≤©ÏúºÎ°ú Í∞ÅÍ∞Å Ïù¥ÎèôÌèâÍ∑†ÌïúÍ∞íÏùÑ Íµ¨ÌïòÏó¨Îùº(Ïò§Îãµ)

In [ ]:
df[['RPT', 'VAL']].rolling(window=7).mean()

RPT        VAL
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
6569  11.868571   9.362857
6570  11.904286   9.595714
6571  13.017143  10.011429
6572  13.285714  10.118571
6573  14.951429  11.801429

[6574 rows x 2 columns]

In [54]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv')

Q76 ÎÖÑ-Ïõî-Ïùº:Ïãú Ïª¨ÎüºÏùÑ pandasÏóêÏÑú Ïù∏ÏãùÌï† Ïàò ÏûàÎäî datetime ÌòïÌÉúÎ°ú Î≥ÄÍ≤ΩÌïòÎùº. ÏÑúÏö∏ÏãúÏùò Ï†úÍ≥µÎç∞Ïù¥ÌÑ∞Ïùò Í≤ΩÏö∞ 0ÏãúÍ∞Ä 24ÏãúÎ°ú ÌëúÌòÑÎêúÎã§

In [55]:
df.head()

(ÎÖÑ-Ïõî-Ïùº:Ïãú) PM10Îì±Í∏â  PM10 PM2.5Îì±Í∏â  PM2.5 Ïò§Ï°¥Îì±Í∏â     Ïò§Ï°¥ Ïù¥ÏÇ∞ÌôîÏßàÏÜåÎì±Í∏â  Ïù¥ÏÇ∞ÌôîÏßàÏÜå  \
0  2021-05-15:15     Î≥¥ÌÜµ  47.0      Î≥¥ÌÜµ   19.0   Ï¢ãÏùå  0.017      Ï¢ãÏùå  0.023   
1  2021-05-15:14     Î≥¥ÌÜµ  43.0      Î≥¥ÌÜµ   20.0   Ï¢ãÏùå  0.024      Ï¢ãÏùå  0.019   
2  2021-05-15:13     Î≥¥ÌÜµ  34.0      Î≥¥ÌÜµ   24.0   Î≥¥ÌÜµ  0.035      Ï¢ãÏùå  0.017   
3  2021-05-15:12     Î≥¥ÌÜµ  41.0      Î≥¥ÌÜµ   27.0   Î≥¥ÌÜµ  0.037      Ï¢ãÏùå  0.020   
4  2021-05-15:11     Î≥¥ÌÜµ  51.0      Î≥¥ÌÜµ   34.0   Î≥¥ÌÜµ  0.033      Ï¢ãÏùå  0.023   

  ÏùºÏÇ∞ÌôîÌÉÑÏÜåÎì±Í∏â  ÏùºÏÇ∞ÌôîÌÉÑÏÜå ÏïÑÌô©ÏÇ∞Í∞ÄÏä§Îì±Í∏â  ÏïÑÌô©ÏÇ∞Í∞ÄÏä§  
0      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.003  
1      Ï¢ãÏùå    0.3      Ï¢ãÏùå  0.003  
2      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.004  
3      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.004  
4      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.005

In [56]:
def func(x):
  year, month, day = x.split(':')[0].split("-")
  hour = x.split(':')[1]
  if hour == '24':
    hour = '00'
  return pd.to_datetime(f"{year}-{month}-{day} {hour}:00:00")
df['(ÎÖÑ-Ïõî-Ïùº:Ïãú)'] = df['(ÎÖÑ-Ïõî-Ïùº:Ïãú)'].apply(func)

In [57]:
df.head()

(ÎÖÑ-Ïõî-Ïùº:Ïãú) PM10Îì±Í∏â  PM10 PM2.5Îì±Í∏â  PM2.5 Ïò§Ï°¥Îì±Í∏â     Ïò§Ï°¥ Ïù¥ÏÇ∞ÌôîÏßàÏÜåÎì±Í∏â  Ïù¥ÏÇ∞ÌôîÏßàÏÜå  \
0 2021-05-15 15:00:00     Î≥¥ÌÜµ  47.0      Î≥¥ÌÜµ   19.0   Ï¢ãÏùå  0.017      Ï¢ãÏùå  0.023   
1 2021-05-15 14:00:00     Î≥¥ÌÜµ  43.0      Î≥¥ÌÜµ   20.0   Ï¢ãÏùå  0.024      Ï¢ãÏùå  0.019   
2 2021-05-15 13:00:00     Î≥¥ÌÜµ  34.0      Î≥¥ÌÜµ   24.0   Î≥¥ÌÜµ  0.035      Ï¢ãÏùå  0.017   
3 2021-05-15 12:00:00     Î≥¥ÌÜµ  41.0      Î≥¥ÌÜµ   27.0   Î≥¥ÌÜµ  0.037      Ï¢ãÏùå  0.020   
4 2021-05-15 11:00:00     Î≥¥ÌÜµ  51.0      Î≥¥ÌÜµ   34.0   Î≥¥ÌÜµ  0.033      Ï¢ãÏùå  0.023   

  ÏùºÏÇ∞ÌôîÌÉÑÏÜåÎì±Í∏â  ÏùºÏÇ∞ÌôîÌÉÑÏÜå ÏïÑÌô©ÏÇ∞Í∞ÄÏä§Îì±Í∏â  ÏïÑÌô©ÏÇ∞Í∞ÄÏä§  
0      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.003  
1      Ï¢ãÏùå    0.3      Ï¢ãÏùå  0.003  
2      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.004  
3      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.004  
4      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.005

Q77 ÏùºÏûêÎ≥Ñ ÏòÅÏñ¥ÏöîÏùº Ïù¥Î¶ÑÏùÑ dayName Ïª¨ÎüºÏóê Ï†ÄÏû•ÌïòÎùº

In [58]:
df['dayName'] = df['(ÎÖÑ-Ïõî-Ïùº:Ïãú)'].dt.day_name()

df['dayName']

0       Saturday
1       Saturday
2       Saturday
3       Saturday
4       Saturday
          ...   
1234    Thursday
1235    Thursday
1236    Thursday
1237    Thursday
1238    Thursday
Name: dayName, Length: 1239, dtype: object

Q78 ÏùºÏûêÎ≥Ñ Í∞Å PM10Îì±Í∏âÏùò ÎπàÎèÑÏàòÎ•º ÌååÏïÖÌïòÎùº

In [59]:
df.groupby([df['dayName'], df['PM10Îì±Í∏â']]).size()


dayName    PM10Îì±Í∏â
Friday     ÎÇòÏÅ®         32
           Îß§Ïö∞ÎÇòÏÅ®       18
           Î≥¥ÌÜµ        116
           Ï¢ãÏùå         23
Monday     ÎÇòÏÅ®          1
           Îß§Ïö∞ÎÇòÏÅ®       22
           Î≥¥ÌÜµ         83
           Ï¢ãÏùå         62
Saturday   ÎÇòÏÅ®         29
           Îß§Ïö∞ÎÇòÏÅ®       27
           Î≥¥ÌÜµ         70
           Ï¢ãÏùå         56
Sunday     ÎÇòÏÅ®          2
           Î≥¥ÌÜµ         68
           Ï¢ãÏùå         98
Thursday   ÎÇòÏÅ®         41
           Î≥¥ÌÜµ        145
           Ï¢ãÏùå          5
Tuesday    ÎÇòÏÅ®         13
           Îß§Ïö∞ÎÇòÏÅ®        9
           Î≥¥ÌÜµ         71
           Ï¢ãÏùå         75
Wednesday  ÎÇòÏÅ®         27
           Î≥¥ÌÜµ         98
           Ï¢ãÏùå         42
dtype: int64

Q79 ÏãúÍ∞ÑÏù¥ Ïó∞ÏÜçÏ†ÅÏúºÎ°ú Ï°¥Ïû¨ÌïòÎ©∞ Í≤∞Ï∏°ÏπòÍ∞Ä ÏóÜÎäîÏßÄ ÌôïÏù∏ÌïòÎùº

In [60]:
len(df['(ÎÖÑ-Ïõî-Ïùº:Ïãú)'].diff().unique()) > 1

True

Q80 Ïò§Ï†Ñ 10ÏãúÏôÄ Ïò§ÌõÑ 10Ïãú(22Ïãú)Ïùò PM10Ïùò ÌèâÍ∑†Í∞íÏùÑ Í∞ÅÍ∞Å Íµ¨ÌïòÏó¨Îùº

In [61]:
print(df[df['(ÎÖÑ-Ïõî-Ïùº:Ïãú)'].dt.hour == 10]['PM10'].mean())
print()
print(df[df['(ÎÖÑ-Ïõî-Ïùº:Ïãú)'].dt.hour == 22]['PM10'].mean())


70.38461538461539

69.94117647058823


Q81 ÎÇ†Ïßú Ïª¨ÎüºÏùÑ indexÎ°ú ÎßåÎì§Ïñ¥Îùº

df.set_index

In [62]:
df.set_index('(ÎÖÑ-Ïõî-Ïùº:Ïãú)',inplace=True,drop=True)

df

PM10Îì±Í∏â  PM10 PM2.5Îì±Í∏â  PM2.5 Ïò§Ï°¥Îì±Í∏â     Ïò§Ï°¥ Ïù¥ÏÇ∞ÌôîÏßàÏÜåÎì±Í∏â  Ïù¥ÏÇ∞ÌôîÏßàÏÜå  \
(ÎÖÑ-Ïõî-Ïùº:Ïãú)                                                                    
2021-05-15 15:00:00     Î≥¥ÌÜµ  47.0      Î≥¥ÌÜµ   19.0   Ï¢ãÏùå  0.017      Ï¢ãÏùå  0.023   
2021-05-15 14:00:00     Î≥¥ÌÜµ  43.0      Î≥¥ÌÜµ   20.0   Ï¢ãÏùå  0.024      Ï¢ãÏùå  0.019   
2021-05-15 13:00:00     Î≥¥ÌÜµ  34.0      Î≥¥ÌÜµ   24.0   Î≥¥ÌÜµ  0.035      Ï¢ãÏùå  0.017   
2021-05-15 12:00:00     Î≥¥ÌÜµ  41.0      Î≥¥ÌÜµ   27.0   Î≥¥ÌÜµ  0.037      Ï¢ãÏùå  0.020   
2021-05-15 11:00:00     Î≥¥ÌÜµ  51.0      Î≥¥ÌÜµ   34.0   Î≥¥ÌÜµ  0.033      Ï¢ãÏùå  0.023   
...                    ...   ...     ...    ...  ...    ...     ...    ...   
2021-03-25 05:00:00     Î≥¥ÌÜµ  39.0      Î≥¥ÌÜµ   18.0   Ï¢ãÏùå  0.026      Ï¢ãÏùå  0.025   
2021-03-25 04:00:00     Î≥¥ÌÜµ  34.0      Ï¢ãÏùå   15.0   Ï¢ãÏùå  0.017      Î≥¥ÌÜµ  0.033   
2021-03-25 03:00:00     Î≥¥ÌÜµ  35.0      Ï¢ãÏùå   13.0   Ï¢ãÏùå  0.029      Ï¢ãÏùå  0.025   
2021-03-25 02:00:00     Î≥¥ÌÜµ  35.0      Ï¢ãÏùå   13.0   Î≥¥ÌÜµ  0.031      Ï¢ãÏùå  0.025   
2021-03-25 01:00:00     Î≥¥ÌÜµ  42.0      Ï¢ãÏùå   13.0   Ï¢ãÏùå  0.022      Î≥¥ÌÜµ  0.037   

                    ÏùºÏÇ∞ÌôîÌÉÑÏÜåÎì±Í∏â  ÏùºÏÇ∞ÌôîÌÉÑÏÜå ÏïÑÌô©ÏÇ∞Í∞ÄÏä§Îì±Í∏â  ÏïÑÌô©ÏÇ∞Í∞ÄÏä§   dayName  
(ÎÖÑ-Ïõî-Ïùº:Ïãú)                                                    
2021-05-15 15:00:00      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.003  Saturday  
2021-05-15 14:00:00      Ï¢ãÏùå    0.3      Ï¢ãÏùå  0.003  Saturday  
2021-05-15 13:00:00      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.004  Saturday  
2021-05-15 12:00:00      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.004  Saturday  
2021-05-15 11:00:00      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.005  Saturday  
...                     ...    ...     ...    ...       ...  
2021-03-25 05:00:00      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.003  Thursday  
2021-03-25 04:00:00      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.002  Thursday  
2021-03-25 03:00:00      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.003  Thursday  
2021-03-25 02:00:00      Ï¢ãÏùå    0.3      Ï¢ãÏùå  0.003  Thursday  
2021-03-25 01:00:00      Ï¢ãÏùå    0.4      Ï¢ãÏùå  0.003  Thursday  

[1239 rows x 13 columns]

Q82 Îç∞Ïù¥ÌÑ∞Î•º Ï£ºÎã®ÏúÑÎ°ú ÎΩëÏïÑÏÑú ÏµúÏÜå,ÏµúÎåÄ ÌèâÍ∑†, ÌëúÏ§ÄÌëúÏ∞®Î•º Íµ¨ÌïòÏó¨Îùº

In [67]:
# ÏàòÏπòÌòï Ïª¨ÎüºÎßå ÏÑ†ÌÉù
numeric_df = df.select_dtypes(exclude='object')

# Ï£º Îã®ÏúÑ Î¶¨ÏÉòÌîåÎßÅ Î∞è ÌÜµÍ≥Ñ ÏßëÍ≥Ñ
result = numeric_df.resample('W').agg(['min', 'max', 'mean', 'std'])
result

PM10                                 PM2.5                    \
             min     max        mean         std   min    max       mean   
(ÎÖÑ-Ïõî-Ïùº:Ïãú)                                                                  
2021-03-28   6.0   160.0   72.427083   43.230775   4.0  113.0  44.562500   
2021-04-04   3.0   598.0   97.047619  129.961800   1.0  120.0  23.048193   
2021-04-11  17.0   102.0   41.232143   16.308395   7.0   70.0  21.863095   
2021-04-18   3.0   367.0   48.072289   43.262352   2.0   38.0  17.006024   
2021-04-25  17.0   126.0   55.059524   26.713988   7.0   61.0  26.357143   
2021-05-02   3.0    97.0   40.606061   24.816816   1.0   43.0  16.650602   
2021-05-09   8.0  1024.0  161.678571  239.669016   3.0  172.0  34.720238   
2021-05-16  16.0   111.0   40.104478   21.934033   7.0   76.0  21.664179   

                          Ïò§Ï°¥         ...     Ïù¥ÏÇ∞ÌôîÏßàÏÜå           ÏùºÏÇ∞ÌôîÌÉÑÏÜå       \
                  std    min    max  ...      mean       std   min  max   
(ÎÖÑ-Ïõî-Ïùº:Ïãú)                            ...                                  
2021-03-28  29.429242  0.002  0.085  ...  0.044302  0.023753   0.3  1.4   
2021-04-04  22.410984  0.003  0.055  ...  0.027917  0.014987   0.3  0.9   
2021-04-11  11.458817  0.009  0.070  ...  0.022851  0.009997   0.3  0.7   
2021-04-18   7.821878  0.002  0.070  ...  0.023518  0.013238   0.3  0.6   
2021-04-25  13.125961  0.006  0.090  ...  0.028643  0.014637   0.3  0.8   
2021-05-02   8.848124  0.003  0.064  ...  0.020361  0.011630   0.3  0.6   
2021-05-09  39.798734  0.002  0.073  ...  0.024265  0.012405   0.3  1.0   
2021-05-16  15.648846  0.004  0.123  ...  0.030754  0.009528   0.3  0.8   

                                ÏïÑÌô©ÏÇ∞Í∞ÄÏä§                             
                mean       std    min    max      mean       std  
(ÎÖÑ-Ïõî-Ïùº:Ïãú)                                                         
2021-03-28  0.611458  0.231184  0.002  0.006  0.003260  0.000965  
2021-04-04  0.444048  0.135674  0.002  0.004  0.002738  0.000539  
2021-04-11  0.391071  0.088791  0.002  0.004  0.002744  0.000569  
2021-04-18  0.385542  0.083314  0.002  0.004  0.002464  0.000579  
2021-04-25  0.457143  0.122142  0.001  0.011  0.003631  0.001763  
2021-05-02  0.392771  0.092485  0.001  0.006  0.002524  0.000768  
2021-05-09  0.419277  0.103230  0.002  0.004  0.002771  0.000579  
2021-05-16  0.441045  0.094362  0.001  0.006  0.002455  0.001702  

[8 rows x 24 columns]

# 06_Pivot

In [116]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/under5MortalityRate.csv')

Q83 IndicatorÏùÑ ÏÇ≠Ï†úÌïòÍ≥† First Tooltip Ïª¨ÎüºÏóêÏÑú Ïã†Î¢∞Íµ¨Í∞ÑÏóê Ìï¥ÎãπÌïòÎäî ÌëúÌòÑÏùÑ ÏßÄÏõåÎùº



In [117]:
df.drop('Indicator',axis=1,inplace=True)

df['First Tooltip'] = df['First Tooltip'].map(lambda x: x.split('[')[0])

df

Location  Period        Dim1 First Tooltip
0      Afghanistan    2019  Both sexes        60.27 
1      Afghanistan    2019        Male        63.83 
2      Afghanistan    2019      Female        56.57 
3      Afghanistan    2018  Both sexes        62.54 
4      Afghanistan    2018        Male        66.08 
...            ...     ...         ...           ...
29994  Timor-Leste    2002  Both sexes        96.97 
29995  Timor-Leste    2002        Male        102.6 
29996  Timor-Leste    2002      Female        91.04 
29997  Timor-Leste    2001  Both sexes        102.5 
29998  Timor-Leste    2001        Male        108.2 

[29999 rows x 4 columns]

Q84 ÎÖÑÎèÑÍ∞Ä 2015ÎÖÑ Ïù¥ÏÉÅ, Dim1Ïù¥ Both sexesÏù∏ ÏºÄÏù¥Ïä§Îßå Ï∂îÏ∂úÌïòÎùº

In [122]:
result = df[(df['Period'] >= 2015)&(df['Dim1'] == "Both sexes")]

result

Location  Period        Dim1 First Tooltip
0      Afghanistan    2019  Both sexes        60.27 
3      Afghanistan    2018  Both sexes        62.54 
6      Afghanistan    2017  Both sexes        64.94 
9      Afghanistan    2016  Both sexes        67.57 
12     Afghanistan    2015  Both sexes        70.44 
...            ...     ...         ...           ...
29943  Timor-Leste    2019  Both sexes        44.22 
29946  Timor-Leste    2018  Both sexes        45.62 
29949  Timor-Leste    2017  Both sexes        47.27 
29952  Timor-Leste    2016  Both sexes        49.01 
29955  Timor-Leste    2015  Both sexes        50.76 

[860 rows x 4 columns]

Q85 84Î≤à Î¨∏Ï†úÏóêÏÑú Ï∂îÏ∂úÌïú Îç∞Ïù¥ÌÑ∞Î°ú ÏïÑÎûòÏôÄ Í∞ôÏù¥ ÎÇòÎùºÏóê Îî∞Î•∏ ÎÖÑÎèÑÎ≥Ñ ÏÇ¨ÎßùÎ•†ÏùÑ Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÌôî ÌïòÎùº

In [134]:
result = result.pivot(index='Location',columns='Period',values='First Tooltip')

result

Period                                       2015    2016    2017    2018  \
Location                                                                    
Afghanistan                                70.44   67.57   64.94   62.54    
Albania                                     9.57    9.42    9.42    9.53    
Algeria                                    25.18   24.79   24.32   23.81    
Andorra                                     3.53    3.37    3.22    3.09    
Angola                                      88.2   84.21   80.62   77.67    
...                                           ...     ...     ...     ...   
Syrian Arab Republic                       23.18   23.27   22.97   22.11    
Tajikistan                                 37.75   36.82   35.81    34.8    
Thailand                                    10.8   10.32    9.86    9.42    
The former Yugoslav Republic of Macedonia  12.97   11.97    9.94    7.83    
Timor-Leste                                50.76   49.01   47.27   45.62    

Period                                       2019  
Location                                           
Afghanistan                                60.27   
Albania                                     9.68   
Algeria                                    23.26   
Andorra                                     2.97   
Angola                                     74.69   
...                                           ...  
Syrian Arab Republic                       21.53   
Tajikistan                                 33.78   
Thailand                                    9.01   
The former Yugoslav Republic of Macedonia   6.12   
Timor-Leste                                44.22   

[172 rows x 5 columns]

Q86 Dim1Ïóê Îî∞Î•∏ ÎÖÑÎèÑÎ≥Ñ ÏÇ¨ÎßùÎπÑÏú®Ïùò ÌèâÍ∑†ÏùÑ Íµ¨ÌïòÎùº

In [140]:
df['First Tooltip'] = df['First Tooltip'].astype(float)

df[['Dim1','Period', 'First Tooltip']].pivot_table(index='Dim1',columns='Period',values='First Tooltip',aggfunc='mean')

Period            1950        1951        1952        1953        1954  \
Dim1                                                                     
Both sexes  147.700816  155.537544  157.811094  156.147206  154.539857   
Female      140.909796  149.210175  151.516094  150.250882  148.688286   
Male        154.151224  161.538246  163.760781  161.742059  160.081000   

Period            1955        1956        1957        1958        1959  ...  \
Dim1                                                                    ...   
Both sexes  155.797179  159.241163  156.170114  150.813222  150.574000  ...   
Female      149.843205  153.048721  149.988295  144.719667  144.451474  ...   
Male        161.456923  165.089535  162.015000  156.573556  156.375053  ...   

Period           2010       2011       2012       2013       2014       2015  \
Dim1                                                                           
Both sexes  37.718488  35.573663  34.290988  33.099360  32.053314  31.012093   
Female      34.953023  32.877616  31.654070  30.521337  29.524302  28.544360   
Male        40.340174  38.140291  36.793081  35.543663  34.446105  33.354302   

Period           2016       2017       2018       2019  
Dim1                                                    
Both sexes  29.956337  29.030465  28.083837  27.191744  
Female      27.542035  26.675291  25.782616  24.945349  
Male        32.242616  31.273198  30.283023  29.350349  

[3 rows x 70 columns]

In [141]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/winter.csv')

Q87 Îç∞Ïù¥ÌÑ∞ÏóêÏÑú ÌïúÍµ≠ KOR Îç∞Ïù¥ÌÑ∞Îßå Ï∂îÏ∂úÌïòÎùº

In [149]:
KOR_df = df[df['Country'] == 'KOR']

KOR_df

Year         City    Sport                 Discipline          Athlete  \
2652  1992  Albertville  Skating  Short Track Speed Skating      LEE, Jun-Ho   
2653  1992  Albertville  Skating  Short Track Speed Skating     KIM, Ki-Hoon   
2671  1992  Albertville  Skating  Short Track Speed Skating     KIM, Ki-Hoon   
2672  1992  Albertville  Skating  Short Track Speed Skating      LEE, Jun-Ho   
2673  1992  Albertville  Skating  Short Track Speed Skating       MO, Ji-Soo   
...    ...          ...      ...                        ...              ...   
5528  2014        Sochi  Skating  Short Track Speed Skating   PARK, Seung-Hi   
5544  2014        Sochi  Skating              Speed skating   JOO, Hyong Jun   
5545  2014        Sochi  Skating              Speed skating   KIM, Cheol Min   
5546  2014        Sochi  Skating              Speed skating  LEE, Seung Hoon   
5565  2014        Sochi  Skating              Speed skating    LEE, Sang Hwa   

     Country Gender         Event   Medal  
2652     KOR    Men         1000M  Bronze  
2653     KOR    Men         1000M    Gold  
2671     KOR    Men   5000M Relay    Gold  
2672     KOR    Men   5000M Relay    Gold  
2673     KOR    Men   5000M Relay    Gold  
...      ...    ...           ...     ...  
5528     KOR  Women          500M  Bronze  
5544     KOR    Men  Team Pursuit  Silver  
5545     KOR    Men  Team Pursuit  Silver  
5546     KOR    Men  Team Pursuit  Silver  
5565     KOR  Women          500M    Gold  

[87 rows x 9 columns]

Q88 ÌïúÍµ≠ Ïò¨Î¶ºÌîΩ Î©îÎã¨Î¶¨Ïä§Ìä∏ Îç∞Ïù¥ÌÑ∞ÏóêÏÑú ÎÖÑÎèÑÏóê Îî∞Î•∏ medal Í∞ØÏàòÎ•º Îç∞Ïù¥ÌÑ∞ÌîÑÎ†àÏûÑÌôî ÌïòÎùº

In [151]:
KOR_df.pivot_table(index='Year',columns='Medal',aggfunc='size').fillna(0)

Medal  Bronze  Gold  Silver
Year                       
1992      1.0   5.0     1.0
1994      1.0   8.0     1.0
1998      2.0   6.0     4.0
2002      0.0   5.0     2.0
2006      2.0  14.0     3.0
2010      2.0   6.0    10.0
2014      2.0   7.0     5.0

Q89 Ï†ÑÏ≤¥ Îç∞Ïù¥ÌÑ∞ÏóêÏÑú sportÏ¢ÖÎ•òÏóê Îî∞Î•∏ ÏÑ±Î≥ÑÏàòÎ•º Íµ¨ÌïòÏó¨Îùº

In [152]:
df

Year      City     Sport Discipline               Athlete Country  \
0     1924  Chamonix  Biathlon   Biathlon           BERTHET, G.     FRA   
1     1924  Chamonix  Biathlon   Biathlon        MANDRILLON, C.     FRA   
2     1924  Chamonix  Biathlon   Biathlon   MANDRILLON, Maurice     FRA   
3     1924  Chamonix  Biathlon   Biathlon       VANDELLE, Andr√©     FRA   
4     1924  Chamonix  Biathlon   Biathlon  AUFDENBLATTEN, Adolf     SUI   
...    ...       ...       ...        ...                   ...     ...   
5765  2014     Sochi    Skiing  Snowboard          JONES, Jenny     GBR   
5766  2014     Sochi    Skiing  Snowboard       ANDERSON, Jamie     USA   
5767  2014     Sochi    Skiing  Snowboard    MALTAIS, Dominique     CAN   
5768  2014     Sochi    Skiing  Snowboard          SAMKOVA, Eva     CZE   
5769  2014     Sochi    Skiing  Snowboard      TRESPEUCH, Chloe     FRA   

     Gender            Event   Medal  
0       Men  Military Patrol  Bronze  
1       Men  Military Patrol  Bronze  
2       Men  Military Patrol  Bronze  
3       Men  Military Patrol  Bronze  
4       Men  Military Patrol    Gold  
...     ...              ...     ...  
5765  Women       Slopestyle  Bronze  
5766  Women       Slopestyle    Gold  
5767  Women  Snowboard Cross  Silver  
5768  Women  Snowboard Cross    Gold  
5769  Women  Snowboard Cross  Bronze  

[5770 rows x 9 columns]

In [153]:
df.pivot_table(index ='Sport', columns = 'Gender', aggfunc = 'size' )

Gender       Men  Women
Sport                  
Biathlon     270    150
Bobsleigh    416     36
Curling       97     75
Ice Hockey  1231    305
Luge         135     45
Skating      665    564
Skiing      1130    651

Q90 Ï†ÑÏ≤¥ Îç∞Ïù¥ÌÑ∞ÏóêÏÑú DisciplineÏ¢ÖÎ•òÏóê Îî∞Î•∏ Îî∞Î•∏ MedalÏàòÎ•º Íµ¨ÌïòÏó¨Îùº

In [154]:
df.pivot_table(index ='Discipline', columns = 'Medal', aggfunc = 'size')

Medal                      Bronze  Gold  Silver
Discipline                                     
Alpine Skiing                 141   143     144
Biathlon                      139   140     141
Bobsleigh                     147   134     141
Cross Country Skiing          263   264     262
Curling                        56    58      58
Figure skating                118   122     119
Freestyle Skiing               34    34      34
Ice Hockey                    512   510     514
Luge                           60    62      58
Nordic Combined                55    55      55
Short Track Speed Skating      96    97      97
Skeleton                       10    10      10
Ski Jumping                    68    69      70
Snowboard                      30    30      30
Speed skating                 190   193     197

In [155]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/mergeTEst.csv',index_col= 0)

df1 = df.iloc[:4,:]
df2 = df.iloc[4:,:]

display(df1)
display(df2)

2010    2011    2012    2013   2014    2015    2016    2017  \
Location                                                                     
Afghanistan  64.023  61.640  59.367  57.170  55.08  53.107  51.267  49.560   
Albania      11.803  10.807   9.943   9.267   8.79   8.493   8.363   8.363   
Algeria      23.540  22.907  22.450  22.117  21.85  21.587  21.257  20.850   
Andorra       4.240   4.033   3.843   3.667   3.49   3.330   3.187   3.060   

               2018    2019  
Location                     
Afghanistan  47.983  46.453  
Albania       8.453   8.597  
Algeria      20.407  19.930  
Andorra       2.933   2.827

2010    2011    2012    2013    2014    2015    2016  \
Location                                                                      
Angola               75.713  71.280  67.233  63.570  60.430  57.757  55.510   
Antigua and Barbuda   8.667   8.223   7.807   7.420   7.070   6.757   6.483   
Argentina            12.887  12.380  11.840  11.283  10.733  10.203   9.683   
Armenia              16.497  15.677  14.897  14.170  13.477  12.817  12.183   
Australia             3.993   3.803   3.623   3.467   3.343   3.253   3.183   
Austria               3.573   3.463   3.333   3.210   3.113   3.043   2.987   

                       2017    2018    2019  
Location                                     
Angola               53.460  51.757  50.093  
Antigua and Barbuda   6.230   6.000   5.783  
Argentina             9.177   8.680   8.227  
Armenia              11.583  11.007  10.497  
Australia             3.137   3.090   3.047  
Austria               2.943   2.897   2.843

Q91 df1Í≥º df2 Îç∞Ïù¥ÌÑ∞Î•º ÌïòÎÇòÏùò Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏúºÎ°ú Ìï©Ï≥êÎùº

In [158]:
total = pd.concat([df1, df2])

total

2010    2011    2012    2013    2014    2015    2016  \
Location                                                                      
Afghanistan          64.023  61.640  59.367  57.170  55.080  53.107  51.267   
Albania              11.803  10.807   9.943   9.267   8.790   8.493   8.363   
Algeria              23.540  22.907  22.450  22.117  21.850  21.587  21.257   
Andorra               4.240   4.033   3.843   3.667   3.490   3.330   3.187   
Angola               75.713  71.280  67.233  63.570  60.430  57.757  55.510   
Antigua and Barbuda   8.667   8.223   7.807   7.420   7.070   6.757   6.483   
Argentina            12.887  12.380  11.840  11.283  10.733  10.203   9.683   
Armenia              16.497  15.677  14.897  14.170  13.477  12.817  12.183   
Australia             3.993   3.803   3.623   3.467   3.343   3.253   3.183   
Austria               3.573   3.463   3.333   3.210   3.113   3.043   2.987   

                       2017    2018    2019  
Location                                     
Afghanistan          49.560  47.983  46.453  
Albania               8.363   8.453   8.597  
Algeria              20.850  20.407  19.930  
Andorra               3.060   2.933   2.827  
Angola               53.460  51.757  50.093  
Antigua and Barbuda   6.230   6.000   5.783  
Argentina             9.177   8.680   8.227  
Armenia              11.583  11.007  10.497  
Australia             3.137   3.090   3.047  
Austria               2.943   2.897   2.843

In [159]:
df3 = df.iloc[:2,:4]
df4 = df.iloc[5:,3:]

display(df3)
display(df4)

2010    2011    2012    2013
Location                                   
Afghanistan  64.023  61.640  59.367  57.170
Albania      11.803  10.807   9.943   9.267

2013    2014    2015    2016    2017    2018    2019
Location                                                                   
Antigua and Barbuda   7.420   7.070   6.757   6.483   6.230   6.000   5.783
Argentina            11.283  10.733  10.203   9.683   9.177   8.680   8.227
Armenia              14.170  13.477  12.817  12.183  11.583  11.007  10.497
Australia             3.467   3.343   3.253   3.183   3.137   3.090   3.047
Austria               3.210   3.113   3.043   2.987   2.943   2.897   2.843

Q92 df3Í≥º df4 Îç∞Ïù¥ÌÑ∞Î•º ÌïòÎÇòÏùò Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏúºÎ°ú Ìï©Ï≥êÎùº. ÎëòÎã§ Ìè¨Ìï®ÌïòÍ≥† ÏûàÎäî ÎÖÑÎèÑÏóê ÎåÄÌï¥ÏÑúÎßå Í≥†Î†§ÌïúÎã§

In [160]:
pd.concat([df3, df4], join = 'inner')

2013
Location                   
Afghanistan          57.170
Albania               9.267
Antigua and Barbuda   7.420
Argentina            11.283
Armenia              14.170
Australia             3.467
Austria               3.210

Q93 df3Í≥º df4 Îç∞Ïù¥ÌÑ∞Î•º ÌïòÎÇòÏùò Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏúºÎ°ú Ìï©Ï≥êÎùº. Î™®Îì† Ïª¨ÎüºÏùÑ Ìè¨Ìï®ÌïòÍ≥†, Í≤∞Ï∏°ÏπòÎäî 0ÏúºÎ°ú ÎåÄÏ≤¥ÌïúÎã§

In [162]:
pd.concat([df3, df4], join = 'outer').fillna(0)

2010    2011    2012    2013    2014    2015    2016  \
Location                                                                      
Afghanistan          64.023  61.640  59.367  57.170   0.000   0.000   0.000   
Albania              11.803  10.807   9.943   9.267   0.000   0.000   0.000   
Antigua and Barbuda   0.000   0.000   0.000   7.420   7.070   6.757   6.483   
Argentina             0.000   0.000   0.000  11.283  10.733  10.203   9.683   
Armenia               0.000   0.000   0.000  14.170  13.477  12.817  12.183   
Australia             0.000   0.000   0.000   3.467   3.343   3.253   3.183   
Austria               0.000   0.000   0.000   3.210   3.113   3.043   2.987   

                       2017    2018    2019  
Location                                     
Afghanistan           0.000   0.000   0.000  
Albania               0.000   0.000   0.000  
Antigua and Barbuda   6.230   6.000   5.783  
Argentina             9.177   8.680   8.227  
Armenia              11.583  11.007  10.497  
Australia             3.137   3.090   3.047  
Austria               2.943   2.897   2.843

In [163]:
df5 = df.T.iloc[:7,:3]
df6 = df.T.iloc[6:,2:5]

display(df5)
display(df6)

Location  Afghanistan  Albania  Algeria
2010           64.023   11.803   23.540
2011           61.640   10.807   22.907
2012           59.367    9.943   22.450
2013           57.170    9.267   22.117
2014           55.080    8.790   21.850
2015           53.107    8.493   21.587
2016           51.267    8.363   21.257

Location  Algeria  Andorra  Angola
2016       21.257    3.187  55.510
2017       20.850    3.060  53.460
2018       20.407    2.933  51.757
2019       19.930    2.827  50.093

Q94 df5Í≥º df6 Îç∞Ïù¥ÌÑ∞Î•º ÌïòÎÇòÏùò Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏúºÎ°ú mergeÌï®ÏàòÎ•º Ïù¥Ïö©ÌïòÏó¨ Ìï©Ï≥êÎùº. AlgeriaÏª¨ÎüºÏùÑ keyÎ°ú ÌïòÍ≥† Îëê Îç∞Ïù¥ÌÑ∞ Î™®Îëê Ìè¨Ìï®ÌïòÎäî Îç∞Ïù¥ÌÑ∞Îßå Ï∂úÎ†•ÌïòÎùº

In [164]:
pd.merge(df5, df6, on = 'Algeria', how = 'inner')

Location  Afghanistan  Albania  Algeria  Andorra  Angola
0              51.267    8.363   21.257    3.187   55.51

Q95 df5Í≥º df6 Îç∞Ïù¥ÌÑ∞Î•º ÌïòÎÇòÏùò Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑÏúºÎ°ú mergeÌï®ÏàòÎ•º Ïù¥Ïö©ÌïòÏó¨ Ìï©Ï≥êÎùº. AlgeriaÏª¨ÎüºÏùÑ keyÎ°ú ÌïòÍ≥† Ìï©ÏßëÌï©ÏúºÎ°ú Ìï©Ï≥êÎùº

In [165]:
pd.merge(df5, df6, on = 'Algeria', how = 'outer')

Location  Afghanistan  Albania  Algeria  Andorra  Angola
0                 NaN      NaN   19.930    2.827  50.093
1                 NaN      NaN   20.407    2.933  51.757
2                 NaN      NaN   20.850    3.060  53.460
3              51.267    8.363   21.257    3.187  55.510
4              53.107    8.493   21.587      NaN     NaN
5              55.080    8.790   21.850      NaN     NaN
6              57.170    9.267   22.117      NaN     NaN
7              59.367    9.943   22.450      NaN     NaN
8              61.640   10.807   22.907      NaN     NaN
9              64.023   11.803   23.540      NaN     NaN